//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPiServer.Campaign.Extensions.SessionService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebserviceException", Namespace="urn:api.broadmail.de/soap11/Session")]
    [System.SerializableAttribute()]
    public partial class WebserviceException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private object causeField;
        
        private string messageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public object cause {
            get {
                return this.causeField;
            }
            set {
                if ((object.ReferenceEquals(this.causeField, value) != true)) {
                    this.causeField = value;
                    this.RaisePropertyChanged("cause");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:api.broadmail.de/soap11/Session", ConfigurationName="SessionService.SessionWebservice")]
    public interface SessionWebservice {
        
        // CODEGEN: Generating message contract since element name in0 from namespace urn:api.broadmail.de/soap11/Session is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.SessionService.WebserviceException), Action="", Name="fault")]
        EPiServer.Campaign.Extensions.SessionService.setMediaTypeResponse setMediaType(EPiServer.Campaign.Extensions.SessionService.setMediaTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.SessionService.setMediaTypeResponse> setMediaTypeAsync(EPiServer.Campaign.Extensions.SessionService.setMediaTypeRequest request);
        
        // CODEGEN: Generating message contract since element name in0 from namespace urn:api.broadmail.de/soap11/Session is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.SessionService.WebserviceException), Action="", Name="fault")]
        EPiServer.Campaign.Extensions.SessionService.getMediaTypeResponse getMediaType(EPiServer.Campaign.Extensions.SessionService.getMediaTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.SessionService.getMediaTypeResponse> getMediaTypeAsync(EPiServer.Campaign.Extensions.SessionService.getMediaTypeRequest request);
        
        // CODEGEN: Generating message contract since element name in0 from namespace urn:api.broadmail.de/soap11/Session is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.SessionService.WebserviceException), Action="", Name="fault")]
        EPiServer.Campaign.Extensions.SessionService.logoutResponse logout(EPiServer.Campaign.Extensions.SessionService.logoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.SessionService.logoutResponse> logoutAsync(EPiServer.Campaign.Extensions.SessionService.logoutRequest request);
        
        // CODEGEN: Generating message contract since element name in1 from namespace urn:api.broadmail.de/soap11/Session is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.SessionService.WebserviceException), Action="", Name="fault")]
        EPiServer.Campaign.Extensions.SessionService.loginResponse login(EPiServer.Campaign.Extensions.SessionService.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.SessionService.loginResponse> loginAsync(EPiServer.Campaign.Extensions.SessionService.loginRequest request);
        
        // CODEGEN: Generating message contract since element name in0 from namespace urn:api.broadmail.de/soap11/Session is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.SessionService.WebserviceException), Action="", Name="fault")]
        EPiServer.Campaign.Extensions.SessionService.setLocaleResponse setLocale(EPiServer.Campaign.Extensions.SessionService.setLocaleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.SessionService.setLocaleResponse> setLocaleAsync(EPiServer.Campaign.Extensions.SessionService.setLocaleRequest request);
        
        // CODEGEN: Generating message contract since element name in0 from namespace urn:api.broadmail.de/soap11/Session is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.SessionService.WebserviceException), Action="", Name="fault")]
        EPiServer.Campaign.Extensions.SessionService.getLocaleResponse getLocale(EPiServer.Campaign.Extensions.SessionService.getLocaleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.SessionService.getLocaleResponse> getLocaleAsync(EPiServer.Campaign.Extensions.SessionService.getLocaleRequest request);
        
        // CODEGEN: Generating message contract since element name getVersionReturn from namespace urn:api.broadmail.de/soap11/Session is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.SessionService.WebserviceException), Action="", Name="fault")]
        EPiServer.Campaign.Extensions.SessionService.getVersionResponse getVersion(EPiServer.Campaign.Extensions.SessionService.getVersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.SessionService.getVersionResponse> getVersionAsync(EPiServer.Campaign.Extensions.SessionService.getVersionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setMediaTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setMediaType", Namespace="urn:api.broadmail.de/soap11/Session", Order=0)]
        public EPiServer.Campaign.Extensions.SessionService.setMediaTypeRequestBody Body;
        
        public setMediaTypeRequest() {
        }
        
        public setMediaTypeRequest(EPiServer.Campaign.Extensions.SessionService.setMediaTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:api.broadmail.de/soap11/Session")]
    public partial class setMediaTypeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string in0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string in1;
        
        public setMediaTypeRequestBody() {
        }
        
        public setMediaTypeRequestBody(string in0, string in1) {
            this.in0 = in0;
            this.in1 = in1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setMediaTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setMediaTypeResponse", Namespace="urn:api.broadmail.de/soap11/Session", Order=0)]
        public EPiServer.Campaign.Extensions.SessionService.setMediaTypeResponseBody Body;
        
        public setMediaTypeResponse() {
        }
        
        public setMediaTypeResponse(EPiServer.Campaign.Extensions.SessionService.setMediaTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class setMediaTypeResponseBody {
        
        public setMediaTypeResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMediaTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMediaType", Namespace="urn:api.broadmail.de/soap11/Session", Order=0)]
        public EPiServer.Campaign.Extensions.SessionService.getMediaTypeRequestBody Body;
        
        public getMediaTypeRequest() {
        }
        
        public getMediaTypeRequest(EPiServer.Campaign.Extensions.SessionService.getMediaTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:api.broadmail.de/soap11/Session")]
    public partial class getMediaTypeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string in0;
        
        public getMediaTypeRequestBody() {
        }
        
        public getMediaTypeRequestBody(string in0) {
            this.in0 = in0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMediaTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMediaTypeResponse", Namespace="urn:api.broadmail.de/soap11/Session", Order=0)]
        public EPiServer.Campaign.Extensions.SessionService.getMediaTypeResponseBody Body;
        
        public getMediaTypeResponse() {
        }
        
        public getMediaTypeResponse(EPiServer.Campaign.Extensions.SessionService.getMediaTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:api.broadmail.de/soap11/Session")]
    public partial class getMediaTypeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getMediaTypeReturn;
        
        public getMediaTypeResponseBody() {
        }
        
        public getMediaTypeResponseBody(string getMediaTypeReturn) {
            this.getMediaTypeReturn = getMediaTypeReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logoutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logout", Namespace="urn:api.broadmail.de/soap11/Session", Order=0)]
        public EPiServer.Campaign.Extensions.SessionService.logoutRequestBody Body;
        
        public logoutRequest() {
        }
        
        public logoutRequest(EPiServer.Campaign.Extensions.SessionService.logoutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:api.broadmail.de/soap11/Session")]
    public partial class logoutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string in0;
        
        public logoutRequestBody() {
        }
        
        public logoutRequestBody(string in0) {
            this.in0 = in0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logoutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logoutResponse", Namespace="urn:api.broadmail.de/soap11/Session", Order=0)]
        public EPiServer.Campaign.Extensions.SessionService.logoutResponseBody Body;
        
        public logoutResponse() {
        }
        
        public logoutResponse(EPiServer.Campaign.Extensions.SessionService.logoutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class logoutResponseBody {
        
        public logoutResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="login", Namespace="urn:api.broadmail.de/soap11/Session", Order=0)]
        public EPiServer.Campaign.Extensions.SessionService.loginRequestBody Body;
        
        public loginRequest() {
        }
        
        public loginRequest(EPiServer.Campaign.Extensions.SessionService.loginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:api.broadmail.de/soap11/Session")]
    public partial class loginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long in0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string in1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string in2;
        
        public loginRequestBody() {
        }
        
        public loginRequestBody(long in0, string in1, string in2) {
            this.in0 = in0;
            this.in1 = in1;
            this.in2 = in2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginResponse", Namespace="urn:api.broadmail.de/soap11/Session", Order=0)]
        public EPiServer.Campaign.Extensions.SessionService.loginResponseBody Body;
        
        public loginResponse() {
        }
        
        public loginResponse(EPiServer.Campaign.Extensions.SessionService.loginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:api.broadmail.de/soap11/Session")]
    public partial class loginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginReturn;
        
        public loginResponseBody() {
        }
        
        public loginResponseBody(string loginReturn) {
            this.loginReturn = loginReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setLocaleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setLocale", Namespace="urn:api.broadmail.de/soap11/Session", Order=0)]
        public EPiServer.Campaign.Extensions.SessionService.setLocaleRequestBody Body;
        
        public setLocaleRequest() {
        }
        
        public setLocaleRequest(EPiServer.Campaign.Extensions.SessionService.setLocaleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:api.broadmail.de/soap11/Session")]
    public partial class setLocaleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string in0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string in1;
        
        public setLocaleRequestBody() {
        }
        
        public setLocaleRequestBody(string in0, string in1) {
            this.in0 = in0;
            this.in1 = in1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setLocaleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setLocaleResponse", Namespace="urn:api.broadmail.de/soap11/Session", Order=0)]
        public EPiServer.Campaign.Extensions.SessionService.setLocaleResponseBody Body;
        
        public setLocaleResponse() {
        }
        
        public setLocaleResponse(EPiServer.Campaign.Extensions.SessionService.setLocaleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class setLocaleResponseBody {
        
        public setLocaleResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLocaleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getLocale", Namespace="urn:api.broadmail.de/soap11/Session", Order=0)]
        public EPiServer.Campaign.Extensions.SessionService.getLocaleRequestBody Body;
        
        public getLocaleRequest() {
        }
        
        public getLocaleRequest(EPiServer.Campaign.Extensions.SessionService.getLocaleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:api.broadmail.de/soap11/Session")]
    public partial class getLocaleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string in0;
        
        public getLocaleRequestBody() {
        }
        
        public getLocaleRequestBody(string in0) {
            this.in0 = in0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLocaleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getLocaleResponse", Namespace="urn:api.broadmail.de/soap11/Session", Order=0)]
        public EPiServer.Campaign.Extensions.SessionService.getLocaleResponseBody Body;
        
        public getLocaleResponse() {
        }
        
        public getLocaleResponse(EPiServer.Campaign.Extensions.SessionService.getLocaleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:api.broadmail.de/soap11/Session")]
    public partial class getLocaleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getLocaleReturn;
        
        public getLocaleResponseBody() {
        }
        
        public getLocaleResponseBody(string getLocaleReturn) {
            this.getLocaleReturn = getLocaleReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getVersion", Namespace="urn:api.broadmail.de/soap11/Session", Order=0)]
        public EPiServer.Campaign.Extensions.SessionService.getVersionRequestBody Body;
        
        public getVersionRequest() {
        }
        
        public getVersionRequest(EPiServer.Campaign.Extensions.SessionService.getVersionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getVersionRequestBody {
        
        public getVersionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getVersionResponse", Namespace="urn:api.broadmail.de/soap11/Session", Order=0)]
        public EPiServer.Campaign.Extensions.SessionService.getVersionResponseBody Body;
        
        public getVersionResponse() {
        }
        
        public getVersionResponse(EPiServer.Campaign.Extensions.SessionService.getVersionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:api.broadmail.de/soap11/Session")]
    public partial class getVersionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getVersionReturn;
        
        public getVersionResponseBody() {
        }
        
        public getVersionResponseBody(string getVersionReturn) {
            this.getVersionReturn = getVersionReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SessionWebserviceChannel : EPiServer.Campaign.Extensions.SessionService.SessionWebservice, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SessionWebserviceClient : System.ServiceModel.ClientBase<EPiServer.Campaign.Extensions.SessionService.SessionWebservice>, EPiServer.Campaign.Extensions.SessionService.SessionWebservice {
        
        public SessionWebserviceClient() {
        }
        
        public SessionWebserviceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SessionWebserviceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SessionWebserviceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SessionWebserviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EPiServer.Campaign.Extensions.SessionService.setMediaTypeResponse EPiServer.Campaign.Extensions.SessionService.SessionWebservice.setMediaType(EPiServer.Campaign.Extensions.SessionService.setMediaTypeRequest request) {
            return base.Channel.setMediaType(request);
        }
        
        public void setMediaType(string in0, string in1) {
            EPiServer.Campaign.Extensions.SessionService.setMediaTypeRequest inValue = new EPiServer.Campaign.Extensions.SessionService.setMediaTypeRequest();
            inValue.Body = new EPiServer.Campaign.Extensions.SessionService.setMediaTypeRequestBody();
            inValue.Body.in0 = in0;
            inValue.Body.in1 = in1;
            EPiServer.Campaign.Extensions.SessionService.setMediaTypeResponse retVal = ((EPiServer.Campaign.Extensions.SessionService.SessionWebservice)(this)).setMediaType(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.SessionService.setMediaTypeResponse> EPiServer.Campaign.Extensions.SessionService.SessionWebservice.setMediaTypeAsync(EPiServer.Campaign.Extensions.SessionService.setMediaTypeRequest request) {
            return base.Channel.setMediaTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.SessionService.setMediaTypeResponse> setMediaTypeAsync(string in0, string in1) {
            EPiServer.Campaign.Extensions.SessionService.setMediaTypeRequest inValue = new EPiServer.Campaign.Extensions.SessionService.setMediaTypeRequest();
            inValue.Body = new EPiServer.Campaign.Extensions.SessionService.setMediaTypeRequestBody();
            inValue.Body.in0 = in0;
            inValue.Body.in1 = in1;
            return ((EPiServer.Campaign.Extensions.SessionService.SessionWebservice)(this)).setMediaTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EPiServer.Campaign.Extensions.SessionService.getMediaTypeResponse EPiServer.Campaign.Extensions.SessionService.SessionWebservice.getMediaType(EPiServer.Campaign.Extensions.SessionService.getMediaTypeRequest request) {
            return base.Channel.getMediaType(request);
        }
        
        public string getMediaType(string in0) {
            EPiServer.Campaign.Extensions.SessionService.getMediaTypeRequest inValue = new EPiServer.Campaign.Extensions.SessionService.getMediaTypeRequest();
            inValue.Body = new EPiServer.Campaign.Extensions.SessionService.getMediaTypeRequestBody();
            inValue.Body.in0 = in0;
            EPiServer.Campaign.Extensions.SessionService.getMediaTypeResponse retVal = ((EPiServer.Campaign.Extensions.SessionService.SessionWebservice)(this)).getMediaType(inValue);
            return retVal.Body.getMediaTypeReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.SessionService.getMediaTypeResponse> EPiServer.Campaign.Extensions.SessionService.SessionWebservice.getMediaTypeAsync(EPiServer.Campaign.Extensions.SessionService.getMediaTypeRequest request) {
            return base.Channel.getMediaTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.SessionService.getMediaTypeResponse> getMediaTypeAsync(string in0) {
            EPiServer.Campaign.Extensions.SessionService.getMediaTypeRequest inValue = new EPiServer.Campaign.Extensions.SessionService.getMediaTypeRequest();
            inValue.Body = new EPiServer.Campaign.Extensions.SessionService.getMediaTypeRequestBody();
            inValue.Body.in0 = in0;
            return ((EPiServer.Campaign.Extensions.SessionService.SessionWebservice)(this)).getMediaTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EPiServer.Campaign.Extensions.SessionService.logoutResponse EPiServer.Campaign.Extensions.SessionService.SessionWebservice.logout(EPiServer.Campaign.Extensions.SessionService.logoutRequest request) {
            return base.Channel.logout(request);
        }
        
        public void logout(string in0) {
            EPiServer.Campaign.Extensions.SessionService.logoutRequest inValue = new EPiServer.Campaign.Extensions.SessionService.logoutRequest();
            inValue.Body = new EPiServer.Campaign.Extensions.SessionService.logoutRequestBody();
            inValue.Body.in0 = in0;
            EPiServer.Campaign.Extensions.SessionService.logoutResponse retVal = ((EPiServer.Campaign.Extensions.SessionService.SessionWebservice)(this)).logout(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.SessionService.logoutResponse> EPiServer.Campaign.Extensions.SessionService.SessionWebservice.logoutAsync(EPiServer.Campaign.Extensions.SessionService.logoutRequest request) {
            return base.Channel.logoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.SessionService.logoutResponse> logoutAsync(string in0) {
            EPiServer.Campaign.Extensions.SessionService.logoutRequest inValue = new EPiServer.Campaign.Extensions.SessionService.logoutRequest();
            inValue.Body = new EPiServer.Campaign.Extensions.SessionService.logoutRequestBody();
            inValue.Body.in0 = in0;
            return ((EPiServer.Campaign.Extensions.SessionService.SessionWebservice)(this)).logoutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EPiServer.Campaign.Extensions.SessionService.loginResponse EPiServer.Campaign.Extensions.SessionService.SessionWebservice.login(EPiServer.Campaign.Extensions.SessionService.loginRequest request) {
            return base.Channel.login(request);
        }
        
        public string login(long in0, string in1, string in2) {
            EPiServer.Campaign.Extensions.SessionService.loginRequest inValue = new EPiServer.Campaign.Extensions.SessionService.loginRequest();
            inValue.Body = new EPiServer.Campaign.Extensions.SessionService.loginRequestBody();
            inValue.Body.in0 = in0;
            inValue.Body.in1 = in1;
            inValue.Body.in2 = in2;
            EPiServer.Campaign.Extensions.SessionService.loginResponse retVal = ((EPiServer.Campaign.Extensions.SessionService.SessionWebservice)(this)).login(inValue);
            return retVal.Body.loginReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.SessionService.loginResponse> EPiServer.Campaign.Extensions.SessionService.SessionWebservice.loginAsync(EPiServer.Campaign.Extensions.SessionService.loginRequest request) {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.SessionService.loginResponse> loginAsync(long in0, string in1, string in2) {
            EPiServer.Campaign.Extensions.SessionService.loginRequest inValue = new EPiServer.Campaign.Extensions.SessionService.loginRequest();
            inValue.Body = new EPiServer.Campaign.Extensions.SessionService.loginRequestBody();
            inValue.Body.in0 = in0;
            inValue.Body.in1 = in1;
            inValue.Body.in2 = in2;
            return ((EPiServer.Campaign.Extensions.SessionService.SessionWebservice)(this)).loginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EPiServer.Campaign.Extensions.SessionService.setLocaleResponse EPiServer.Campaign.Extensions.SessionService.SessionWebservice.setLocale(EPiServer.Campaign.Extensions.SessionService.setLocaleRequest request) {
            return base.Channel.setLocale(request);
        }
        
        public void setLocale(string in0, string in1) {
            EPiServer.Campaign.Extensions.SessionService.setLocaleRequest inValue = new EPiServer.Campaign.Extensions.SessionService.setLocaleRequest();
            inValue.Body = new EPiServer.Campaign.Extensions.SessionService.setLocaleRequestBody();
            inValue.Body.in0 = in0;
            inValue.Body.in1 = in1;
            EPiServer.Campaign.Extensions.SessionService.setLocaleResponse retVal = ((EPiServer.Campaign.Extensions.SessionService.SessionWebservice)(this)).setLocale(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.SessionService.setLocaleResponse> EPiServer.Campaign.Extensions.SessionService.SessionWebservice.setLocaleAsync(EPiServer.Campaign.Extensions.SessionService.setLocaleRequest request) {
            return base.Channel.setLocaleAsync(request);
        }
        
        public System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.SessionService.setLocaleResponse> setLocaleAsync(string in0, string in1) {
            EPiServer.Campaign.Extensions.SessionService.setLocaleRequest inValue = new EPiServer.Campaign.Extensions.SessionService.setLocaleRequest();
            inValue.Body = new EPiServer.Campaign.Extensions.SessionService.setLocaleRequestBody();
            inValue.Body.in0 = in0;
            inValue.Body.in1 = in1;
            return ((EPiServer.Campaign.Extensions.SessionService.SessionWebservice)(this)).setLocaleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EPiServer.Campaign.Extensions.SessionService.getLocaleResponse EPiServer.Campaign.Extensions.SessionService.SessionWebservice.getLocale(EPiServer.Campaign.Extensions.SessionService.getLocaleRequest request) {
            return base.Channel.getLocale(request);
        }
        
        public string getLocale(string in0) {
            EPiServer.Campaign.Extensions.SessionService.getLocaleRequest inValue = new EPiServer.Campaign.Extensions.SessionService.getLocaleRequest();
            inValue.Body = new EPiServer.Campaign.Extensions.SessionService.getLocaleRequestBody();
            inValue.Body.in0 = in0;
            EPiServer.Campaign.Extensions.SessionService.getLocaleResponse retVal = ((EPiServer.Campaign.Extensions.SessionService.SessionWebservice)(this)).getLocale(inValue);
            return retVal.Body.getLocaleReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.SessionService.getLocaleResponse> EPiServer.Campaign.Extensions.SessionService.SessionWebservice.getLocaleAsync(EPiServer.Campaign.Extensions.SessionService.getLocaleRequest request) {
            return base.Channel.getLocaleAsync(request);
        }
        
        public System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.SessionService.getLocaleResponse> getLocaleAsync(string in0) {
            EPiServer.Campaign.Extensions.SessionService.getLocaleRequest inValue = new EPiServer.Campaign.Extensions.SessionService.getLocaleRequest();
            inValue.Body = new EPiServer.Campaign.Extensions.SessionService.getLocaleRequestBody();
            inValue.Body.in0 = in0;
            return ((EPiServer.Campaign.Extensions.SessionService.SessionWebservice)(this)).getLocaleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EPiServer.Campaign.Extensions.SessionService.getVersionResponse EPiServer.Campaign.Extensions.SessionService.SessionWebservice.getVersion(EPiServer.Campaign.Extensions.SessionService.getVersionRequest request) {
            return base.Channel.getVersion(request);
        }
        
        public string getVersion() {
            EPiServer.Campaign.Extensions.SessionService.getVersionRequest inValue = new EPiServer.Campaign.Extensions.SessionService.getVersionRequest();
            inValue.Body = new EPiServer.Campaign.Extensions.SessionService.getVersionRequestBody();
            EPiServer.Campaign.Extensions.SessionService.getVersionResponse retVal = ((EPiServer.Campaign.Extensions.SessionService.SessionWebservice)(this)).getVersion(inValue);
            return retVal.Body.getVersionReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.SessionService.getVersionResponse> EPiServer.Campaign.Extensions.SessionService.SessionWebservice.getVersionAsync(EPiServer.Campaign.Extensions.SessionService.getVersionRequest request) {
            return base.Channel.getVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.SessionService.getVersionResponse> getVersionAsync() {
            EPiServer.Campaign.Extensions.SessionService.getVersionRequest inValue = new EPiServer.Campaign.Extensions.SessionService.getVersionRequest();
            inValue.Body = new EPiServer.Campaign.Extensions.SessionService.getVersionRequestBody();
            return ((EPiServer.Campaign.Extensions.SessionService.SessionWebservice)(this)).getVersionAsync(inValue);
        }
    }
}
