//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPiServer.Campaign.Extensions.CouponCode {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap11.api.broadmail")]
    public partial class WebserviceException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object causeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public object cause {
            get {
                return this.causeField;
            }
            set {
                this.causeField = value;
                this.RaisePropertyChanged("cause");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:api.broadmail.de/soap11/addons/CouponCode", ConfigurationName="CouponCode.CouponCodeWebservice")]
    public interface CouponCodeWebservice {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.CouponCode.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="addReturn")]
        bool add(string in0, long in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="addReturn")]
        System.Threading.Tasks.Task<bool> addAsync(string in0, long in1, string in2);
        
        // CODEGEN: Parameter 'addAllReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.CouponCode.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="addAllReturn")]
        EPiServer.Campaign.Extensions.CouponCode.addAllResponse addAll(EPiServer.Campaign.Extensions.CouponCode.addAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.CouponCode.addAllResponse> addAllAsync(EPiServer.Campaign.Extensions.CouponCode.addAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.CouponCode.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="removeReturn")]
        bool remove(string in0, long in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="removeReturn")]
        System.Threading.Tasks.Task<bool> removeAsync(string in0, long in1, string in2);
        
        // CODEGEN: Parameter 'removeAllReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.CouponCode.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="removeAllReturn")]
        EPiServer.Campaign.Extensions.CouponCode.removeAllResponse removeAll(EPiServer.Campaign.Extensions.CouponCode.removeAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.CouponCode.removeAllResponse> removeAllAsync(EPiServer.Campaign.Extensions.CouponCode.removeAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.CouponCode.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getCreatedReturn")]
        System.DateTime getCreated(string in0, long in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getCreatedReturn")]
        System.Threading.Tasks.Task<System.DateTime> getCreatedAsync(string in0, long in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.CouponCode.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getModifiedReturn")]
        System.DateTime getModified(string in0, long in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getModifiedReturn")]
        System.Threading.Tasks.Task<System.DateTime> getModifiedAsync(string in0, long in1, string in2);
        
        // CODEGEN: Parameter 'getAllAssignedReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.CouponCode.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getAllAssignedReturn")]
        EPiServer.Campaign.Extensions.CouponCode.getAllAssignedResponse getAllAssigned(EPiServer.Campaign.Extensions.CouponCode.getAllAssignedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.CouponCode.getAllAssignedResponse> getAllAssignedAsync(EPiServer.Campaign.Extensions.CouponCode.getAllAssignedRequest request);
        
        // CODEGEN: Parameter 'getAllUnAssignedReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.CouponCode.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getAllUnAssignedReturn")]
        EPiServer.Campaign.Extensions.CouponCode.getAllUnAssignedResponse getAllUnAssigned(EPiServer.Campaign.Extensions.CouponCode.getAllUnAssignedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.CouponCode.getAllUnAssignedResponse> getAllUnAssignedAsync(EPiServer.Campaign.Extensions.CouponCode.getAllUnAssignedRequest request);
        
        // CODEGEN: Parameter 'getByMailingAndRecipientIdReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.CouponCode.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getByMailingAndRecipientIdReturn")]
        EPiServer.Campaign.Extensions.CouponCode.getByMailingAndRecipientIdResponse getByMailingAndRecipientId(EPiServer.Campaign.Extensions.CouponCode.getByMailingAndRecipientIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.CouponCode.getByMailingAndRecipientIdResponse> getByMailingAndRecipientIdAsync(EPiServer.Campaign.Extensions.CouponCode.getByMailingAndRecipientIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.CouponCode.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="isUsedReturn")]
        bool isUsed(string in0, long in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="isUsedReturn")]
        System.Threading.Tasks.Task<bool> isUsedAsync(string in0, long in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.CouponCode.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="isAssignedReturn")]
        bool isAssigned(string in0, long in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="isAssignedReturn")]
        System.Threading.Tasks.Task<bool> isAssignedAsync(string in0, long in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.CouponCode.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void markAsUsed(string in0, long in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task markAsUsedAsync(string in0, long in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.CouponCode.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getAssignedRecipientIdReturn")]
        string getAssignedRecipientId(string in0, long in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getAssignedRecipientIdReturn")]
        System.Threading.Tasks.Task<string> getAssignedRecipientIdAsync(string in0, long in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.CouponCode.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getAssignedMailingReturn")]
        long getAssignedMailing(string in0, long in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getAssignedMailingReturn")]
        System.Threading.Tasks.Task<long> getAssignedMailingAsync(string in0, long in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.CouponCode.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getVersionReturn")]
        string getVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getVersionReturn")]
        System.Threading.Tasks.Task<string> getVersionAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addAll", WrapperNamespace="urn:api.broadmail.de/soap11/addons/CouponCode", IsWrapped=true)]
    public partial class addAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/addons/CouponCode", Order=0)]
        public string in0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/addons/CouponCode", Order=1)]
        public long in1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/addons/CouponCode", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("in2")]
        public string[] in2;
        
        public addAllRequest() {
        }
        
        public addAllRequest(string in0, long in1, string[] in2) {
            this.in0 = in0;
            this.in1 = in1;
            this.in2 = in2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addAllResponse", WrapperNamespace="urn:api.broadmail.de/soap11/addons/CouponCode", IsWrapped=true)]
    public partial class addAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/addons/CouponCode", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("addAllReturn")]
        public bool[] addAllReturn;
        
        public addAllResponse() {
        }
        
        public addAllResponse(bool[] addAllReturn) {
            this.addAllReturn = addAllReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeAll", WrapperNamespace="urn:api.broadmail.de/soap11/addons/CouponCode", IsWrapped=true)]
    public partial class removeAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/addons/CouponCode", Order=0)]
        public string in0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/addons/CouponCode", Order=1)]
        public long in1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/addons/CouponCode", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("in2")]
        public string[] in2;
        
        public removeAllRequest() {
        }
        
        public removeAllRequest(string in0, long in1, string[] in2) {
            this.in0 = in0;
            this.in1 = in1;
            this.in2 = in2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeAllResponse", WrapperNamespace="urn:api.broadmail.de/soap11/addons/CouponCode", IsWrapped=true)]
    public partial class removeAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/addons/CouponCode", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("removeAllReturn")]
        public bool[] removeAllReturn;
        
        public removeAllResponse() {
        }
        
        public removeAllResponse(bool[] removeAllReturn) {
            this.removeAllReturn = removeAllReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllAssigned", WrapperNamespace="urn:api.broadmail.de/soap11/addons/CouponCode", IsWrapped=true)]
    public partial class getAllAssignedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/addons/CouponCode", Order=0)]
        public string in0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/addons/CouponCode", Order=1)]
        public long in1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/addons/CouponCode", Order=2)]
        public long in2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/addons/CouponCode", Order=3)]
        public int in3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/addons/CouponCode", Order=4)]
        public int in4;
        
        public getAllAssignedRequest() {
        }
        
        public getAllAssignedRequest(string in0, long in1, long in2, int in3, int in4) {
            this.in0 = in0;
            this.in1 = in1;
            this.in2 = in2;
            this.in3 = in3;
            this.in4 = in4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllAssignedResponse", WrapperNamespace="urn:api.broadmail.de/soap11/addons/CouponCode", IsWrapped=true)]
    public partial class getAllAssignedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/addons/CouponCode", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getAllAssignedReturn")]
        public string[] getAllAssignedReturn;
        
        public getAllAssignedResponse() {
        }
        
        public getAllAssignedResponse(string[] getAllAssignedReturn) {
            this.getAllAssignedReturn = getAllAssignedReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllUnAssigned", WrapperNamespace="urn:api.broadmail.de/soap11/addons/CouponCode", IsWrapped=true)]
    public partial class getAllUnAssignedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/addons/CouponCode", Order=0)]
        public string in0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/addons/CouponCode", Order=1)]
        public long in1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/addons/CouponCode", Order=2)]
        public int in2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/addons/CouponCode", Order=3)]
        public int in3;
        
        public getAllUnAssignedRequest() {
        }
        
        public getAllUnAssignedRequest(string in0, long in1, int in2, int in3) {
            this.in0 = in0;
            this.in1 = in1;
            this.in2 = in2;
            this.in3 = in3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllUnAssignedResponse", WrapperNamespace="urn:api.broadmail.de/soap11/addons/CouponCode", IsWrapped=true)]
    public partial class getAllUnAssignedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/addons/CouponCode", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getAllUnAssignedReturn")]
        public string[] getAllUnAssignedReturn;
        
        public getAllUnAssignedResponse() {
        }
        
        public getAllUnAssignedResponse(string[] getAllUnAssignedReturn) {
            this.getAllUnAssignedReturn = getAllUnAssignedReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getByMailingAndRecipientId", WrapperNamespace="urn:api.broadmail.de/soap11/addons/CouponCode", IsWrapped=true)]
    public partial class getByMailingAndRecipientIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/addons/CouponCode", Order=0)]
        public string in0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/addons/CouponCode", Order=1)]
        public long in1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/addons/CouponCode", Order=2)]
        public long in2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/addons/CouponCode", Order=3)]
        public string in3;
        
        public getByMailingAndRecipientIdRequest() {
        }
        
        public getByMailingAndRecipientIdRequest(string in0, long in1, long in2, string in3) {
            this.in0 = in0;
            this.in1 = in1;
            this.in2 = in2;
            this.in3 = in3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getByMailingAndRecipientIdResponse", WrapperNamespace="urn:api.broadmail.de/soap11/addons/CouponCode", IsWrapped=true)]
    public partial class getByMailingAndRecipientIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/addons/CouponCode", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getByMailingAndRecipientIdReturn")]
        public string[] getByMailingAndRecipientIdReturn;
        
        public getByMailingAndRecipientIdResponse() {
        }
        
        public getByMailingAndRecipientIdResponse(string[] getByMailingAndRecipientIdReturn) {
            this.getByMailingAndRecipientIdReturn = getByMailingAndRecipientIdReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CouponCodeWebserviceChannel : EPiServer.Campaign.Extensions.CouponCode.CouponCodeWebservice, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CouponCodeWebserviceClient : System.ServiceModel.ClientBase<EPiServer.Campaign.Extensions.CouponCode.CouponCodeWebservice>, EPiServer.Campaign.Extensions.CouponCode.CouponCodeWebservice {
        
        public CouponCodeWebserviceClient() {
        }
        
        public CouponCodeWebserviceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CouponCodeWebserviceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CouponCodeWebserviceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CouponCodeWebserviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool add(string in0, long in1, string in2) {
            return base.Channel.add(in0, in1, in2);
        }
        
        public System.Threading.Tasks.Task<bool> addAsync(string in0, long in1, string in2) {
            return base.Channel.addAsync(in0, in1, in2);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EPiServer.Campaign.Extensions.CouponCode.addAllResponse EPiServer.Campaign.Extensions.CouponCode.CouponCodeWebservice.addAll(EPiServer.Campaign.Extensions.CouponCode.addAllRequest request) {
            return base.Channel.addAll(request);
        }
        
        public bool[] addAll(string in0, long in1, string[] in2) {
            EPiServer.Campaign.Extensions.CouponCode.addAllRequest inValue = new EPiServer.Campaign.Extensions.CouponCode.addAllRequest();
            inValue.in0 = in0;
            inValue.in1 = in1;
            inValue.in2 = in2;
            EPiServer.Campaign.Extensions.CouponCode.addAllResponse retVal = ((EPiServer.Campaign.Extensions.CouponCode.CouponCodeWebservice)(this)).addAll(inValue);
            return retVal.addAllReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.CouponCode.addAllResponse> EPiServer.Campaign.Extensions.CouponCode.CouponCodeWebservice.addAllAsync(EPiServer.Campaign.Extensions.CouponCode.addAllRequest request) {
            return base.Channel.addAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.CouponCode.addAllResponse> addAllAsync(string in0, long in1, string[] in2) {
            EPiServer.Campaign.Extensions.CouponCode.addAllRequest inValue = new EPiServer.Campaign.Extensions.CouponCode.addAllRequest();
            inValue.in0 = in0;
            inValue.in1 = in1;
            inValue.in2 = in2;
            return ((EPiServer.Campaign.Extensions.CouponCode.CouponCodeWebservice)(this)).addAllAsync(inValue);
        }
        
        public bool remove(string in0, long in1, string in2) {
            return base.Channel.remove(in0, in1, in2);
        }
        
        public System.Threading.Tasks.Task<bool> removeAsync(string in0, long in1, string in2) {
            return base.Channel.removeAsync(in0, in1, in2);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EPiServer.Campaign.Extensions.CouponCode.removeAllResponse EPiServer.Campaign.Extensions.CouponCode.CouponCodeWebservice.removeAll(EPiServer.Campaign.Extensions.CouponCode.removeAllRequest request) {
            return base.Channel.removeAll(request);
        }
        
        public bool[] removeAll(string in0, long in1, string[] in2) {
            EPiServer.Campaign.Extensions.CouponCode.removeAllRequest inValue = new EPiServer.Campaign.Extensions.CouponCode.removeAllRequest();
            inValue.in0 = in0;
            inValue.in1 = in1;
            inValue.in2 = in2;
            EPiServer.Campaign.Extensions.CouponCode.removeAllResponse retVal = ((EPiServer.Campaign.Extensions.CouponCode.CouponCodeWebservice)(this)).removeAll(inValue);
            return retVal.removeAllReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.CouponCode.removeAllResponse> EPiServer.Campaign.Extensions.CouponCode.CouponCodeWebservice.removeAllAsync(EPiServer.Campaign.Extensions.CouponCode.removeAllRequest request) {
            return base.Channel.removeAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.CouponCode.removeAllResponse> removeAllAsync(string in0, long in1, string[] in2) {
            EPiServer.Campaign.Extensions.CouponCode.removeAllRequest inValue = new EPiServer.Campaign.Extensions.CouponCode.removeAllRequest();
            inValue.in0 = in0;
            inValue.in1 = in1;
            inValue.in2 = in2;
            return ((EPiServer.Campaign.Extensions.CouponCode.CouponCodeWebservice)(this)).removeAllAsync(inValue);
        }
        
        public System.DateTime getCreated(string in0, long in1, string in2) {
            return base.Channel.getCreated(in0, in1, in2);
        }
        
        public System.Threading.Tasks.Task<System.DateTime> getCreatedAsync(string in0, long in1, string in2) {
            return base.Channel.getCreatedAsync(in0, in1, in2);
        }
        
        public System.DateTime getModified(string in0, long in1, string in2) {
            return base.Channel.getModified(in0, in1, in2);
        }
        
        public System.Threading.Tasks.Task<System.DateTime> getModifiedAsync(string in0, long in1, string in2) {
            return base.Channel.getModifiedAsync(in0, in1, in2);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EPiServer.Campaign.Extensions.CouponCode.getAllAssignedResponse EPiServer.Campaign.Extensions.CouponCode.CouponCodeWebservice.getAllAssigned(EPiServer.Campaign.Extensions.CouponCode.getAllAssignedRequest request) {
            return base.Channel.getAllAssigned(request);
        }
        
        public string[] getAllAssigned(string in0, long in1, long in2, int in3, int in4) {
            EPiServer.Campaign.Extensions.CouponCode.getAllAssignedRequest inValue = new EPiServer.Campaign.Extensions.CouponCode.getAllAssignedRequest();
            inValue.in0 = in0;
            inValue.in1 = in1;
            inValue.in2 = in2;
            inValue.in3 = in3;
            inValue.in4 = in4;
            EPiServer.Campaign.Extensions.CouponCode.getAllAssignedResponse retVal = ((EPiServer.Campaign.Extensions.CouponCode.CouponCodeWebservice)(this)).getAllAssigned(inValue);
            return retVal.getAllAssignedReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.CouponCode.getAllAssignedResponse> EPiServer.Campaign.Extensions.CouponCode.CouponCodeWebservice.getAllAssignedAsync(EPiServer.Campaign.Extensions.CouponCode.getAllAssignedRequest request) {
            return base.Channel.getAllAssignedAsync(request);
        }
        
        public System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.CouponCode.getAllAssignedResponse> getAllAssignedAsync(string in0, long in1, long in2, int in3, int in4) {
            EPiServer.Campaign.Extensions.CouponCode.getAllAssignedRequest inValue = new EPiServer.Campaign.Extensions.CouponCode.getAllAssignedRequest();
            inValue.in0 = in0;
            inValue.in1 = in1;
            inValue.in2 = in2;
            inValue.in3 = in3;
            inValue.in4 = in4;
            return ((EPiServer.Campaign.Extensions.CouponCode.CouponCodeWebservice)(this)).getAllAssignedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EPiServer.Campaign.Extensions.CouponCode.getAllUnAssignedResponse EPiServer.Campaign.Extensions.CouponCode.CouponCodeWebservice.getAllUnAssigned(EPiServer.Campaign.Extensions.CouponCode.getAllUnAssignedRequest request) {
            return base.Channel.getAllUnAssigned(request);
        }
        
        public string[] getAllUnAssigned(string in0, long in1, int in2, int in3) {
            EPiServer.Campaign.Extensions.CouponCode.getAllUnAssignedRequest inValue = new EPiServer.Campaign.Extensions.CouponCode.getAllUnAssignedRequest();
            inValue.in0 = in0;
            inValue.in1 = in1;
            inValue.in2 = in2;
            inValue.in3 = in3;
            EPiServer.Campaign.Extensions.CouponCode.getAllUnAssignedResponse retVal = ((EPiServer.Campaign.Extensions.CouponCode.CouponCodeWebservice)(this)).getAllUnAssigned(inValue);
            return retVal.getAllUnAssignedReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.CouponCode.getAllUnAssignedResponse> EPiServer.Campaign.Extensions.CouponCode.CouponCodeWebservice.getAllUnAssignedAsync(EPiServer.Campaign.Extensions.CouponCode.getAllUnAssignedRequest request) {
            return base.Channel.getAllUnAssignedAsync(request);
        }
        
        public System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.CouponCode.getAllUnAssignedResponse> getAllUnAssignedAsync(string in0, long in1, int in2, int in3) {
            EPiServer.Campaign.Extensions.CouponCode.getAllUnAssignedRequest inValue = new EPiServer.Campaign.Extensions.CouponCode.getAllUnAssignedRequest();
            inValue.in0 = in0;
            inValue.in1 = in1;
            inValue.in2 = in2;
            inValue.in3 = in3;
            return ((EPiServer.Campaign.Extensions.CouponCode.CouponCodeWebservice)(this)).getAllUnAssignedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EPiServer.Campaign.Extensions.CouponCode.getByMailingAndRecipientIdResponse EPiServer.Campaign.Extensions.CouponCode.CouponCodeWebservice.getByMailingAndRecipientId(EPiServer.Campaign.Extensions.CouponCode.getByMailingAndRecipientIdRequest request) {
            return base.Channel.getByMailingAndRecipientId(request);
        }
        
        public string[] getByMailingAndRecipientId(string in0, long in1, long in2, string in3) {
            EPiServer.Campaign.Extensions.CouponCode.getByMailingAndRecipientIdRequest inValue = new EPiServer.Campaign.Extensions.CouponCode.getByMailingAndRecipientIdRequest();
            inValue.in0 = in0;
            inValue.in1 = in1;
            inValue.in2 = in2;
            inValue.in3 = in3;
            EPiServer.Campaign.Extensions.CouponCode.getByMailingAndRecipientIdResponse retVal = ((EPiServer.Campaign.Extensions.CouponCode.CouponCodeWebservice)(this)).getByMailingAndRecipientId(inValue);
            return retVal.getByMailingAndRecipientIdReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.CouponCode.getByMailingAndRecipientIdResponse> EPiServer.Campaign.Extensions.CouponCode.CouponCodeWebservice.getByMailingAndRecipientIdAsync(EPiServer.Campaign.Extensions.CouponCode.getByMailingAndRecipientIdRequest request) {
            return base.Channel.getByMailingAndRecipientIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.CouponCode.getByMailingAndRecipientIdResponse> getByMailingAndRecipientIdAsync(string in0, long in1, long in2, string in3) {
            EPiServer.Campaign.Extensions.CouponCode.getByMailingAndRecipientIdRequest inValue = new EPiServer.Campaign.Extensions.CouponCode.getByMailingAndRecipientIdRequest();
            inValue.in0 = in0;
            inValue.in1 = in1;
            inValue.in2 = in2;
            inValue.in3 = in3;
            return ((EPiServer.Campaign.Extensions.CouponCode.CouponCodeWebservice)(this)).getByMailingAndRecipientIdAsync(inValue);
        }
        
        public bool isUsed(string in0, long in1, string in2) {
            return base.Channel.isUsed(in0, in1, in2);
        }
        
        public System.Threading.Tasks.Task<bool> isUsedAsync(string in0, long in1, string in2) {
            return base.Channel.isUsedAsync(in0, in1, in2);
        }
        
        public bool isAssigned(string in0, long in1, string in2) {
            return base.Channel.isAssigned(in0, in1, in2);
        }
        
        public System.Threading.Tasks.Task<bool> isAssignedAsync(string in0, long in1, string in2) {
            return base.Channel.isAssignedAsync(in0, in1, in2);
        }
        
        public void markAsUsed(string in0, long in1, string in2) {
            base.Channel.markAsUsed(in0, in1, in2);
        }
        
        public System.Threading.Tasks.Task markAsUsedAsync(string in0, long in1, string in2) {
            return base.Channel.markAsUsedAsync(in0, in1, in2);
        }
        
        public string getAssignedRecipientId(string in0, long in1, string in2) {
            return base.Channel.getAssignedRecipientId(in0, in1, in2);
        }
        
        public System.Threading.Tasks.Task<string> getAssignedRecipientIdAsync(string in0, long in1, string in2) {
            return base.Channel.getAssignedRecipientIdAsync(in0, in1, in2);
        }
        
        public long getAssignedMailing(string in0, long in1, string in2) {
            return base.Channel.getAssignedMailing(in0, in1, in2);
        }
        
        public System.Threading.Tasks.Task<long> getAssignedMailingAsync(string in0, long in1, string in2) {
            return base.Channel.getAssignedMailingAsync(in0, in1, in2);
        }
        
        public string getVersion() {
            return base.Channel.getVersion();
        }
        
        public System.Threading.Tasks.Task<string> getVersionAsync() {
            return base.Channel.getVersionAsync();
        }
    }
}
