//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPiServer.Campaign.Extensions.MailingReporting {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:api.broadmail.de/soap11/MailingReporting")]
    public partial class WebserviceException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object causeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public object cause {
            get {
                return this.causeField;
            }
            set {
                this.causeField = value;
                this.RaisePropertyChanged("cause");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:api.broadmail.de/soap11/MailingReporting", ConfigurationName="MailingReporting.MailingReportingWebservice")]
    public interface MailingReportingWebservice {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.MailingReporting.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getResponseCountReturn")]
        int getResponseCount(string in0, long in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getResponseCountReturn")]
        System.Threading.Tasks.Task<int> getResponseCountAsync(string in0, long in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.MailingReporting.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getOverallRecipientCountReturn")]
        int getOverallRecipientCount(string in0, long in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getOverallRecipientCountReturn")]
        System.Threading.Tasks.Task<int> getOverallRecipientCountAsync(string in0, long in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.MailingReporting.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getSentRecipientCountReturn")]
        int getSentRecipientCount(string in0, long in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getSentRecipientCountReturn")]
        System.Threading.Tasks.Task<int> getSentRecipientCountAsync(string in0, long in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.MailingReporting.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getFailedRecipientCountReturn")]
        int getFailedRecipientCount(string in0, long in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getFailedRecipientCountReturn")]
        System.Threading.Tasks.Task<int> getFailedRecipientCountAsync(string in0, long in1);
        
        // CODEGEN: Parameter 'getLinkNamesReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.MailingReporting.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getLinkNamesReturn")]
        EPiServer.Campaign.Extensions.MailingReporting.getLinkNamesResponse getLinkNames(EPiServer.Campaign.Extensions.MailingReporting.getLinkNamesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.MailingReporting.getLinkNamesResponse> getLinkNamesAsync(EPiServer.Campaign.Extensions.MailingReporting.getLinkNamesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.MailingReporting.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getUnsubscribeCountReturn")]
        int getUnsubscribeCount(string in0, long in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getUnsubscribeCountReturn")]
        System.Threading.Tasks.Task<int> getUnsubscribeCountAsync(string in0, long in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.MailingReporting.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getClickCountReturn")]
        int getClickCount(string in0, long in1, bool in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getClickCountReturn")]
        System.Threading.Tasks.Task<int> getClickCountAsync(string in0, long in1, bool in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.MailingReporting.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getOpenCountReturn")]
        int getOpenCount(string in0, long in1, bool in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getOpenCountReturn")]
        System.Threading.Tasks.Task<int> getOpenCountAsync(string in0, long in1, bool in2);
        
        // CODEGEN: Parameter 'getLinkUrlsReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.MailingReporting.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getLinkUrlsReturn")]
        EPiServer.Campaign.Extensions.MailingReporting.getLinkUrlsResponse getLinkUrls(EPiServer.Campaign.Extensions.MailingReporting.getLinkUrlsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.MailingReporting.getLinkUrlsResponse> getLinkUrlsAsync(EPiServer.Campaign.Extensions.MailingReporting.getLinkUrlsRequest request);
        
        // CODEGEN: Parameter 'getClickCountByUrlReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.MailingReporting.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getClickCountByUrlReturn")]
        EPiServer.Campaign.Extensions.MailingReporting.getClickCountByUrlResponse getClickCountByUrl(EPiServer.Campaign.Extensions.MailingReporting.getClickCountByUrlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.MailingReporting.getClickCountByUrlResponse> getClickCountByUrlAsync(EPiServer.Campaign.Extensions.MailingReporting.getClickCountByUrlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.MailingReporting.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getVersionReturn")]
        string getVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getVersionReturn")]
        System.Threading.Tasks.Task<string> getVersionAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLinkNames", WrapperNamespace="urn:api.broadmail.de/soap11/MailingReporting", IsWrapped=true)]
    public partial class getLinkNamesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/MailingReporting", Order=0)]
        public string in0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/MailingReporting", Order=1)]
        public long in1;
        
        public getLinkNamesRequest() {
        }
        
        public getLinkNamesRequest(string in0, long in1) {
            this.in0 = in0;
            this.in1 = in1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLinkNamesResponse", WrapperNamespace="urn:api.broadmail.de/soap11/MailingReporting", IsWrapped=true)]
    public partial class getLinkNamesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/MailingReporting", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getLinkNamesReturn")]
        public string[] getLinkNamesReturn;
        
        public getLinkNamesResponse() {
        }
        
        public getLinkNamesResponse(string[] getLinkNamesReturn) {
            this.getLinkNamesReturn = getLinkNamesReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLinkUrls", WrapperNamespace="urn:api.broadmail.de/soap11/MailingReporting", IsWrapped=true)]
    public partial class getLinkUrlsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/MailingReporting", Order=0)]
        public string in0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/MailingReporting", Order=1)]
        public long in1;
        
        public getLinkUrlsRequest() {
        }
        
        public getLinkUrlsRequest(string in0, long in1) {
            this.in0 = in0;
            this.in1 = in1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLinkUrlsResponse", WrapperNamespace="urn:api.broadmail.de/soap11/MailingReporting", IsWrapped=true)]
    public partial class getLinkUrlsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/MailingReporting", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getLinkUrlsReturn")]
        public string[] getLinkUrlsReturn;
        
        public getLinkUrlsResponse() {
        }
        
        public getLinkUrlsResponse(string[] getLinkUrlsReturn) {
            this.getLinkUrlsReturn = getLinkUrlsReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getClickCountByUrl", WrapperNamespace="urn:api.broadmail.de/soap11/MailingReporting", IsWrapped=true)]
    public partial class getClickCountByUrlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/MailingReporting", Order=0)]
        public string in0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/MailingReporting", Order=1)]
        public long in1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/MailingReporting", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("in2")]
        public string[] in2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/MailingReporting", Order=3)]
        public bool in3;
        
        public getClickCountByUrlRequest() {
        }
        
        public getClickCountByUrlRequest(string in0, long in1, string[] in2, bool in3) {
            this.in0 = in0;
            this.in1 = in1;
            this.in2 = in2;
            this.in3 = in3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getClickCountByUrlResponse", WrapperNamespace="urn:api.broadmail.de/soap11/MailingReporting", IsWrapped=true)]
    public partial class getClickCountByUrlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/MailingReporting", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getClickCountByUrlReturn")]
        public int[] getClickCountByUrlReturn;
        
        public getClickCountByUrlResponse() {
        }
        
        public getClickCountByUrlResponse(int[] getClickCountByUrlReturn) {
            this.getClickCountByUrlReturn = getClickCountByUrlReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MailingReportingWebserviceChannel : EPiServer.Campaign.Extensions.MailingReporting.MailingReportingWebservice, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MailingReportingWebserviceClient : System.ServiceModel.ClientBase<EPiServer.Campaign.Extensions.MailingReporting.MailingReportingWebservice>, EPiServer.Campaign.Extensions.MailingReporting.MailingReportingWebservice {
        
        public MailingReportingWebserviceClient() {
        }
        
        public MailingReportingWebserviceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MailingReportingWebserviceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailingReportingWebserviceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailingReportingWebserviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int getResponseCount(string in0, long in1, string in2) {
            return base.Channel.getResponseCount(in0, in1, in2);
        }
        
        public System.Threading.Tasks.Task<int> getResponseCountAsync(string in0, long in1, string in2) {
            return base.Channel.getResponseCountAsync(in0, in1, in2);
        }
        
        public int getOverallRecipientCount(string in0, long in1) {
            return base.Channel.getOverallRecipientCount(in0, in1);
        }
        
        public System.Threading.Tasks.Task<int> getOverallRecipientCountAsync(string in0, long in1) {
            return base.Channel.getOverallRecipientCountAsync(in0, in1);
        }
        
        public int getSentRecipientCount(string in0, long in1) {
            return base.Channel.getSentRecipientCount(in0, in1);
        }
        
        public System.Threading.Tasks.Task<int> getSentRecipientCountAsync(string in0, long in1) {
            return base.Channel.getSentRecipientCountAsync(in0, in1);
        }
        
        public int getFailedRecipientCount(string in0, long in1) {
            return base.Channel.getFailedRecipientCount(in0, in1);
        }
        
        public System.Threading.Tasks.Task<int> getFailedRecipientCountAsync(string in0, long in1) {
            return base.Channel.getFailedRecipientCountAsync(in0, in1);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EPiServer.Campaign.Extensions.MailingReporting.getLinkNamesResponse EPiServer.Campaign.Extensions.MailingReporting.MailingReportingWebservice.getLinkNames(EPiServer.Campaign.Extensions.MailingReporting.getLinkNamesRequest request) {
            return base.Channel.getLinkNames(request);
        }
        
        public string[] getLinkNames(string in0, long in1) {
            EPiServer.Campaign.Extensions.MailingReporting.getLinkNamesRequest inValue = new EPiServer.Campaign.Extensions.MailingReporting.getLinkNamesRequest();
            inValue.in0 = in0;
            inValue.in1 = in1;
            EPiServer.Campaign.Extensions.MailingReporting.getLinkNamesResponse retVal = ((EPiServer.Campaign.Extensions.MailingReporting.MailingReportingWebservice)(this)).getLinkNames(inValue);
            return retVal.getLinkNamesReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.MailingReporting.getLinkNamesResponse> EPiServer.Campaign.Extensions.MailingReporting.MailingReportingWebservice.getLinkNamesAsync(EPiServer.Campaign.Extensions.MailingReporting.getLinkNamesRequest request) {
            return base.Channel.getLinkNamesAsync(request);
        }
        
        public System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.MailingReporting.getLinkNamesResponse> getLinkNamesAsync(string in0, long in1) {
            EPiServer.Campaign.Extensions.MailingReporting.getLinkNamesRequest inValue = new EPiServer.Campaign.Extensions.MailingReporting.getLinkNamesRequest();
            inValue.in0 = in0;
            inValue.in1 = in1;
            return ((EPiServer.Campaign.Extensions.MailingReporting.MailingReportingWebservice)(this)).getLinkNamesAsync(inValue);
        }
        
        public int getUnsubscribeCount(string in0, long in1) {
            return base.Channel.getUnsubscribeCount(in0, in1);
        }
        
        public System.Threading.Tasks.Task<int> getUnsubscribeCountAsync(string in0, long in1) {
            return base.Channel.getUnsubscribeCountAsync(in0, in1);
        }
        
        public int getClickCount(string in0, long in1, bool in2) {
            return base.Channel.getClickCount(in0, in1, in2);
        }
        
        public System.Threading.Tasks.Task<int> getClickCountAsync(string in0, long in1, bool in2) {
            return base.Channel.getClickCountAsync(in0, in1, in2);
        }
        
        public int getOpenCount(string in0, long in1, bool in2) {
            return base.Channel.getOpenCount(in0, in1, in2);
        }
        
        public System.Threading.Tasks.Task<int> getOpenCountAsync(string in0, long in1, bool in2) {
            return base.Channel.getOpenCountAsync(in0, in1, in2);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EPiServer.Campaign.Extensions.MailingReporting.getLinkUrlsResponse EPiServer.Campaign.Extensions.MailingReporting.MailingReportingWebservice.getLinkUrls(EPiServer.Campaign.Extensions.MailingReporting.getLinkUrlsRequest request) {
            return base.Channel.getLinkUrls(request);
        }
        
        public string[] getLinkUrls(string in0, long in1) {
            EPiServer.Campaign.Extensions.MailingReporting.getLinkUrlsRequest inValue = new EPiServer.Campaign.Extensions.MailingReporting.getLinkUrlsRequest();
            inValue.in0 = in0;
            inValue.in1 = in1;
            EPiServer.Campaign.Extensions.MailingReporting.getLinkUrlsResponse retVal = ((EPiServer.Campaign.Extensions.MailingReporting.MailingReportingWebservice)(this)).getLinkUrls(inValue);
            return retVal.getLinkUrlsReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.MailingReporting.getLinkUrlsResponse> EPiServer.Campaign.Extensions.MailingReporting.MailingReportingWebservice.getLinkUrlsAsync(EPiServer.Campaign.Extensions.MailingReporting.getLinkUrlsRequest request) {
            return base.Channel.getLinkUrlsAsync(request);
        }
        
        public System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.MailingReporting.getLinkUrlsResponse> getLinkUrlsAsync(string in0, long in1) {
            EPiServer.Campaign.Extensions.MailingReporting.getLinkUrlsRequest inValue = new EPiServer.Campaign.Extensions.MailingReporting.getLinkUrlsRequest();
            inValue.in0 = in0;
            inValue.in1 = in1;
            return ((EPiServer.Campaign.Extensions.MailingReporting.MailingReportingWebservice)(this)).getLinkUrlsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EPiServer.Campaign.Extensions.MailingReporting.getClickCountByUrlResponse EPiServer.Campaign.Extensions.MailingReporting.MailingReportingWebservice.getClickCountByUrl(EPiServer.Campaign.Extensions.MailingReporting.getClickCountByUrlRequest request) {
            return base.Channel.getClickCountByUrl(request);
        }
        
        public int[] getClickCountByUrl(string in0, long in1, string[] in2, bool in3) {
            EPiServer.Campaign.Extensions.MailingReporting.getClickCountByUrlRequest inValue = new EPiServer.Campaign.Extensions.MailingReporting.getClickCountByUrlRequest();
            inValue.in0 = in0;
            inValue.in1 = in1;
            inValue.in2 = in2;
            inValue.in3 = in3;
            EPiServer.Campaign.Extensions.MailingReporting.getClickCountByUrlResponse retVal = ((EPiServer.Campaign.Extensions.MailingReporting.MailingReportingWebservice)(this)).getClickCountByUrl(inValue);
            return retVal.getClickCountByUrlReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.MailingReporting.getClickCountByUrlResponse> EPiServer.Campaign.Extensions.MailingReporting.MailingReportingWebservice.getClickCountByUrlAsync(EPiServer.Campaign.Extensions.MailingReporting.getClickCountByUrlRequest request) {
            return base.Channel.getClickCountByUrlAsync(request);
        }
        
        public System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.MailingReporting.getClickCountByUrlResponse> getClickCountByUrlAsync(string in0, long in1, string[] in2, bool in3) {
            EPiServer.Campaign.Extensions.MailingReporting.getClickCountByUrlRequest inValue = new EPiServer.Campaign.Extensions.MailingReporting.getClickCountByUrlRequest();
            inValue.in0 = in0;
            inValue.in1 = in1;
            inValue.in2 = in2;
            inValue.in3 = in3;
            return ((EPiServer.Campaign.Extensions.MailingReporting.MailingReportingWebservice)(this)).getClickCountByUrlAsync(inValue);
        }
        
        public string getVersion() {
            return base.Channel.getVersion();
        }
        
        public System.Threading.Tasks.Task<string> getVersionAsync() {
            return base.Channel.getVersionAsync();
        }
    }
}
