//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPiServer.Campaign.Extensions.CouponBlock {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap11.api.broadmail")]
    public partial class WebserviceException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object causeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public object cause {
            get {
                return this.causeField;
            }
            set {
                this.causeField = value;
                this.RaisePropertyChanged("cause");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:api.broadmail.de/soap11/addons/CouponBlock", ConfigurationName="CouponBlock.CouponBlockWebservice")]
    public interface CouponBlockWebservice {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.CouponBlock.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getNameReturn")]
        string getName(string in0, long in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getNameReturn")]
        System.Threading.Tasks.Task<string> getNameAsync(string in0, long in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.CouponBlock.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="removeReturn")]
        bool remove(string in0, long in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="removeReturn")]
        System.Threading.Tasks.Task<bool> removeAsync(string in0, long in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.CouponBlock.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="createReturn")]
        long create(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="createReturn")]
        System.Threading.Tasks.Task<long> createAsync(string in0, string in1, string in2);
        
        // CODEGEN: Parameter 'getAllIdsReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.CouponBlock.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getAllIdsReturn")]
        EPiServer.Campaign.Extensions.CouponBlock.getAllIdsResponse getAllIds(EPiServer.Campaign.Extensions.CouponBlock.getAllIdsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.CouponBlock.getAllIdsResponse> getAllIdsAsync(EPiServer.Campaign.Extensions.CouponBlock.getAllIdsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.CouponBlock.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getCodeCountReturn")]
        long getCodeCount(string in0, long in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getCodeCountReturn")]
        System.Threading.Tasks.Task<long> getCodeCountAsync(string in0, long in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.CouponBlock.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getUnAssignedCodeCountReturn")]
        long getUnAssignedCodeCount(string in0, long in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getUnAssignedCodeCountReturn")]
        System.Threading.Tasks.Task<long> getUnAssignedCodeCountAsync(string in0, long in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.CouponBlock.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getAssignedCodeCountReturn")]
        long getAssignedCodeCount(string in0, long in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getAssignedCodeCountReturn")]
        System.Threading.Tasks.Task<long> getAssignedCodeCountAsync(string in0, long in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.CouponBlock.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getCreatedReturn")]
        System.DateTime getCreated(string in0, long in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getCreatedReturn")]
        System.Threading.Tasks.Task<System.DateTime> getCreatedAsync(string in0, long in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.CouponBlock.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getModifiedReturn")]
        System.DateTime getModified(string in0, long in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getModifiedReturn")]
        System.Threading.Tasks.Task<System.DateTime> getModifiedAsync(string in0, long in1);
        
        // CODEGEN: Parameter 'getAssignedMailingsReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.CouponBlock.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getAssignedMailingsReturn")]
        EPiServer.Campaign.Extensions.CouponBlock.getAssignedMailingsResponse getAssignedMailings(EPiServer.Campaign.Extensions.CouponBlock.getAssignedMailingsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.CouponBlock.getAssignedMailingsResponse> getAssignedMailingsAsync(EPiServer.Campaign.Extensions.CouponBlock.getAssignedMailingsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.CouponBlock.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getVersionReturn")]
        string getVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getVersionReturn")]
        System.Threading.Tasks.Task<string> getVersionAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllIds", WrapperNamespace="urn:api.broadmail.de/soap11/addons/CouponBlock", IsWrapped=true)]
    public partial class getAllIdsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/addons/CouponBlock", Order=0)]
        public string in0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/addons/CouponBlock", Order=1)]
        public string in1;
        
        public getAllIdsRequest() {
        }
        
        public getAllIdsRequest(string in0, string in1) {
            this.in0 = in0;
            this.in1 = in1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllIdsResponse", WrapperNamespace="urn:api.broadmail.de/soap11/addons/CouponBlock", IsWrapped=true)]
    public partial class getAllIdsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/addons/CouponBlock", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getAllIdsReturn")]
        public long[] getAllIdsReturn;
        
        public getAllIdsResponse() {
        }
        
        public getAllIdsResponse(long[] getAllIdsReturn) {
            this.getAllIdsReturn = getAllIdsReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAssignedMailings", WrapperNamespace="urn:api.broadmail.de/soap11/addons/CouponBlock", IsWrapped=true)]
    public partial class getAssignedMailingsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/addons/CouponBlock", Order=0)]
        public string in0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/addons/CouponBlock", Order=1)]
        public long in1;
        
        public getAssignedMailingsRequest() {
        }
        
        public getAssignedMailingsRequest(string in0, long in1) {
            this.in0 = in0;
            this.in1 = in1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAssignedMailingsResponse", WrapperNamespace="urn:api.broadmail.de/soap11/addons/CouponBlock", IsWrapped=true)]
    public partial class getAssignedMailingsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/addons/CouponBlock", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getAssignedMailingsReturn")]
        public long[] getAssignedMailingsReturn;
        
        public getAssignedMailingsResponse() {
        }
        
        public getAssignedMailingsResponse(long[] getAssignedMailingsReturn) {
            this.getAssignedMailingsReturn = getAssignedMailingsReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CouponBlockWebserviceChannel : EPiServer.Campaign.Extensions.CouponBlock.CouponBlockWebservice, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CouponBlockWebserviceClient : System.ServiceModel.ClientBase<EPiServer.Campaign.Extensions.CouponBlock.CouponBlockWebservice>, EPiServer.Campaign.Extensions.CouponBlock.CouponBlockWebservice {
        
        public CouponBlockWebserviceClient() {
        }
        
        public CouponBlockWebserviceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CouponBlockWebserviceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CouponBlockWebserviceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CouponBlockWebserviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getName(string in0, long in1) {
            return base.Channel.getName(in0, in1);
        }
        
        public System.Threading.Tasks.Task<string> getNameAsync(string in0, long in1) {
            return base.Channel.getNameAsync(in0, in1);
        }
        
        public bool remove(string in0, long in1) {
            return base.Channel.remove(in0, in1);
        }
        
        public System.Threading.Tasks.Task<bool> removeAsync(string in0, long in1) {
            return base.Channel.removeAsync(in0, in1);
        }
        
        public long create(string in0, string in1, string in2) {
            return base.Channel.create(in0, in1, in2);
        }
        
        public System.Threading.Tasks.Task<long> createAsync(string in0, string in1, string in2) {
            return base.Channel.createAsync(in0, in1, in2);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EPiServer.Campaign.Extensions.CouponBlock.getAllIdsResponse EPiServer.Campaign.Extensions.CouponBlock.CouponBlockWebservice.getAllIds(EPiServer.Campaign.Extensions.CouponBlock.getAllIdsRequest request) {
            return base.Channel.getAllIds(request);
        }
        
        public long[] getAllIds(string in0, string in1) {
            EPiServer.Campaign.Extensions.CouponBlock.getAllIdsRequest inValue = new EPiServer.Campaign.Extensions.CouponBlock.getAllIdsRequest();
            inValue.in0 = in0;
            inValue.in1 = in1;
            EPiServer.Campaign.Extensions.CouponBlock.getAllIdsResponse retVal = ((EPiServer.Campaign.Extensions.CouponBlock.CouponBlockWebservice)(this)).getAllIds(inValue);
            return retVal.getAllIdsReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.CouponBlock.getAllIdsResponse> EPiServer.Campaign.Extensions.CouponBlock.CouponBlockWebservice.getAllIdsAsync(EPiServer.Campaign.Extensions.CouponBlock.getAllIdsRequest request) {
            return base.Channel.getAllIdsAsync(request);
        }
        
        public System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.CouponBlock.getAllIdsResponse> getAllIdsAsync(string in0, string in1) {
            EPiServer.Campaign.Extensions.CouponBlock.getAllIdsRequest inValue = new EPiServer.Campaign.Extensions.CouponBlock.getAllIdsRequest();
            inValue.in0 = in0;
            inValue.in1 = in1;
            return ((EPiServer.Campaign.Extensions.CouponBlock.CouponBlockWebservice)(this)).getAllIdsAsync(inValue);
        }
        
        public long getCodeCount(string in0, long in1) {
            return base.Channel.getCodeCount(in0, in1);
        }
        
        public System.Threading.Tasks.Task<long> getCodeCountAsync(string in0, long in1) {
            return base.Channel.getCodeCountAsync(in0, in1);
        }
        
        public long getUnAssignedCodeCount(string in0, long in1) {
            return base.Channel.getUnAssignedCodeCount(in0, in1);
        }
        
        public System.Threading.Tasks.Task<long> getUnAssignedCodeCountAsync(string in0, long in1) {
            return base.Channel.getUnAssignedCodeCountAsync(in0, in1);
        }
        
        public long getAssignedCodeCount(string in0, long in1) {
            return base.Channel.getAssignedCodeCount(in0, in1);
        }
        
        public System.Threading.Tasks.Task<long> getAssignedCodeCountAsync(string in0, long in1) {
            return base.Channel.getAssignedCodeCountAsync(in0, in1);
        }
        
        public System.DateTime getCreated(string in0, long in1) {
            return base.Channel.getCreated(in0, in1);
        }
        
        public System.Threading.Tasks.Task<System.DateTime> getCreatedAsync(string in0, long in1) {
            return base.Channel.getCreatedAsync(in0, in1);
        }
        
        public System.DateTime getModified(string in0, long in1) {
            return base.Channel.getModified(in0, in1);
        }
        
        public System.Threading.Tasks.Task<System.DateTime> getModifiedAsync(string in0, long in1) {
            return base.Channel.getModifiedAsync(in0, in1);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EPiServer.Campaign.Extensions.CouponBlock.getAssignedMailingsResponse EPiServer.Campaign.Extensions.CouponBlock.CouponBlockWebservice.getAssignedMailings(EPiServer.Campaign.Extensions.CouponBlock.getAssignedMailingsRequest request) {
            return base.Channel.getAssignedMailings(request);
        }
        
        public long[] getAssignedMailings(string in0, long in1) {
            EPiServer.Campaign.Extensions.CouponBlock.getAssignedMailingsRequest inValue = new EPiServer.Campaign.Extensions.CouponBlock.getAssignedMailingsRequest();
            inValue.in0 = in0;
            inValue.in1 = in1;
            EPiServer.Campaign.Extensions.CouponBlock.getAssignedMailingsResponse retVal = ((EPiServer.Campaign.Extensions.CouponBlock.CouponBlockWebservice)(this)).getAssignedMailings(inValue);
            return retVal.getAssignedMailingsReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.CouponBlock.getAssignedMailingsResponse> EPiServer.Campaign.Extensions.CouponBlock.CouponBlockWebservice.getAssignedMailingsAsync(EPiServer.Campaign.Extensions.CouponBlock.getAssignedMailingsRequest request) {
            return base.Channel.getAssignedMailingsAsync(request);
        }
        
        public System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.CouponBlock.getAssignedMailingsResponse> getAssignedMailingsAsync(string in0, long in1) {
            EPiServer.Campaign.Extensions.CouponBlock.getAssignedMailingsRequest inValue = new EPiServer.Campaign.Extensions.CouponBlock.getAssignedMailingsRequest();
            inValue.in0 = in0;
            inValue.in1 = in1;
            return ((EPiServer.Campaign.Extensions.CouponBlock.CouponBlockWebservice)(this)).getAssignedMailingsAsync(inValue);
        }
        
        public string getVersion() {
            return base.Channel.getVersion();
        }
        
        public System.Threading.Tasks.Task<string> getVersionAsync() {
            return base.Channel.getVersionAsync();
        }
    }
}
