//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPiServer.Campaign.Extensions.MailId {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebserviceException", Namespace="urn:api.broadmail.de/soap11/MailId")]
    [System.SerializableAttribute()]
    public partial class WebserviceException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private object causeField;
        
        private string messageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public object cause {
            get {
                return this.causeField;
            }
            set {
                if ((object.ReferenceEquals(this.causeField, value) != true)) {
                    this.causeField = value;
                    this.RaisePropertyChanged("cause");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:api.broadmail.de/soap11/MailId", ConfigurationName="MailId.MailIdWebservice")]
    public interface MailIdWebservice {
        
        // CODEGEN: Generating message contract since element name in0 from namespace urn:api.broadmail.de/soap11/MailId is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.MailId.WebserviceException), Action="", Name="fault")]
        EPiServer.Campaign.Extensions.MailId.getMailingIdResponse getMailingId(EPiServer.Campaign.Extensions.MailId.getMailingIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.MailId.getMailingIdResponse> getMailingIdAsync(EPiServer.Campaign.Extensions.MailId.getMailingIdRequest request);
        
        // CODEGEN: Generating message contract since element name in0 from namespace urn:api.broadmail.de/soap11/MailId is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.MailId.WebserviceException), Action="", Name="fault")]
        EPiServer.Campaign.Extensions.MailId.getRecipientListIdResponse getRecipientListId(EPiServer.Campaign.Extensions.MailId.getRecipientListIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.MailId.getRecipientListIdResponse> getRecipientListIdAsync(EPiServer.Campaign.Extensions.MailId.getRecipientListIdRequest request);
        
        // CODEGEN: Generating message contract since element name in0 from namespace urn:api.broadmail.de/soap11/MailId is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.MailId.WebserviceException), Action="", Name="fault")]
        EPiServer.Campaign.Extensions.MailId.getRecipientIdResponse getRecipientId(EPiServer.Campaign.Extensions.MailId.getRecipientIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.MailId.getRecipientIdResponse> getRecipientIdAsync(EPiServer.Campaign.Extensions.MailId.getRecipientIdRequest request);
        
        // CODEGEN: Generating message contract since element name in0 from namespace urn:api.broadmail.de/soap11/MailId is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.MailId.WebserviceException), Action="", Name="fault")]
        EPiServer.Campaign.Extensions.MailId.getMandatorIdResponse getMandatorId(EPiServer.Campaign.Extensions.MailId.getMandatorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.MailId.getMandatorIdResponse> getMandatorIdAsync(EPiServer.Campaign.Extensions.MailId.getMandatorIdRequest request);
        
        // CODEGEN: Generating message contract since element name getVersionReturn from namespace urn:api.broadmail.de/soap11/MailId is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.MailId.WebserviceException), Action="", Name="fault")]
        EPiServer.Campaign.Extensions.MailId.getVersionResponse getVersion(EPiServer.Campaign.Extensions.MailId.getVersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.MailId.getVersionResponse> getVersionAsync(EPiServer.Campaign.Extensions.MailId.getVersionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMailingIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMailingId", Namespace="urn:api.broadmail.de/soap11/MailId", Order=0)]
        public EPiServer.Campaign.Extensions.MailId.getMailingIdRequestBody Body;
        
        public getMailingIdRequest() {
        }
        
        public getMailingIdRequest(EPiServer.Campaign.Extensions.MailId.getMailingIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:api.broadmail.de/soap11/MailId")]
    public partial class getMailingIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string in0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string in1;
        
        public getMailingIdRequestBody() {
        }
        
        public getMailingIdRequestBody(string in0, string in1) {
            this.in0 = in0;
            this.in1 = in1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMailingIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMailingIdResponse", Namespace="urn:api.broadmail.de/soap11/MailId", Order=0)]
        public EPiServer.Campaign.Extensions.MailId.getMailingIdResponseBody Body;
        
        public getMailingIdResponse() {
        }
        
        public getMailingIdResponse(EPiServer.Campaign.Extensions.MailId.getMailingIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:api.broadmail.de/soap11/MailId")]
    public partial class getMailingIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long getMailingIdReturn;
        
        public getMailingIdResponseBody() {
        }
        
        public getMailingIdResponseBody(long getMailingIdReturn) {
            this.getMailingIdReturn = getMailingIdReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRecipientListIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRecipientListId", Namespace="urn:api.broadmail.de/soap11/MailId", Order=0)]
        public EPiServer.Campaign.Extensions.MailId.getRecipientListIdRequestBody Body;
        
        public getRecipientListIdRequest() {
        }
        
        public getRecipientListIdRequest(EPiServer.Campaign.Extensions.MailId.getRecipientListIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:api.broadmail.de/soap11/MailId")]
    public partial class getRecipientListIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string in0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string in1;
        
        public getRecipientListIdRequestBody() {
        }
        
        public getRecipientListIdRequestBody(string in0, string in1) {
            this.in0 = in0;
            this.in1 = in1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRecipientListIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRecipientListIdResponse", Namespace="urn:api.broadmail.de/soap11/MailId", Order=0)]
        public EPiServer.Campaign.Extensions.MailId.getRecipientListIdResponseBody Body;
        
        public getRecipientListIdResponse() {
        }
        
        public getRecipientListIdResponse(EPiServer.Campaign.Extensions.MailId.getRecipientListIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:api.broadmail.de/soap11/MailId")]
    public partial class getRecipientListIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long getRecipientListIdReturn;
        
        public getRecipientListIdResponseBody() {
        }
        
        public getRecipientListIdResponseBody(long getRecipientListIdReturn) {
            this.getRecipientListIdReturn = getRecipientListIdReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRecipientIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRecipientId", Namespace="urn:api.broadmail.de/soap11/MailId", Order=0)]
        public EPiServer.Campaign.Extensions.MailId.getRecipientIdRequestBody Body;
        
        public getRecipientIdRequest() {
        }
        
        public getRecipientIdRequest(EPiServer.Campaign.Extensions.MailId.getRecipientIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:api.broadmail.de/soap11/MailId")]
    public partial class getRecipientIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string in0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string in1;
        
        public getRecipientIdRequestBody() {
        }
        
        public getRecipientIdRequestBody(string in0, string in1) {
            this.in0 = in0;
            this.in1 = in1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRecipientIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRecipientIdResponse", Namespace="urn:api.broadmail.de/soap11/MailId", Order=0)]
        public EPiServer.Campaign.Extensions.MailId.getRecipientIdResponseBody Body;
        
        public getRecipientIdResponse() {
        }
        
        public getRecipientIdResponse(EPiServer.Campaign.Extensions.MailId.getRecipientIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:api.broadmail.de/soap11/MailId")]
    public partial class getRecipientIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getRecipientIdReturn;
        
        public getRecipientIdResponseBody() {
        }
        
        public getRecipientIdResponseBody(string getRecipientIdReturn) {
            this.getRecipientIdReturn = getRecipientIdReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMandatorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMandatorId", Namespace="urn:api.broadmail.de/soap11/MailId", Order=0)]
        public EPiServer.Campaign.Extensions.MailId.getMandatorIdRequestBody Body;
        
        public getMandatorIdRequest() {
        }
        
        public getMandatorIdRequest(EPiServer.Campaign.Extensions.MailId.getMandatorIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:api.broadmail.de/soap11/MailId")]
    public partial class getMandatorIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string in0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string in1;
        
        public getMandatorIdRequestBody() {
        }
        
        public getMandatorIdRequestBody(string in0, string in1) {
            this.in0 = in0;
            this.in1 = in1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMandatorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMandatorIdResponse", Namespace="urn:api.broadmail.de/soap11/MailId", Order=0)]
        public EPiServer.Campaign.Extensions.MailId.getMandatorIdResponseBody Body;
        
        public getMandatorIdResponse() {
        }
        
        public getMandatorIdResponse(EPiServer.Campaign.Extensions.MailId.getMandatorIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:api.broadmail.de/soap11/MailId")]
    public partial class getMandatorIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long getMandatorIdReturn;
        
        public getMandatorIdResponseBody() {
        }
        
        public getMandatorIdResponseBody(long getMandatorIdReturn) {
            this.getMandatorIdReturn = getMandatorIdReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getVersion", Namespace="urn:api.broadmail.de/soap11/MailId", Order=0)]
        public EPiServer.Campaign.Extensions.MailId.getVersionRequestBody Body;
        
        public getVersionRequest() {
        }
        
        public getVersionRequest(EPiServer.Campaign.Extensions.MailId.getVersionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getVersionRequestBody {
        
        public getVersionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getVersionResponse", Namespace="urn:api.broadmail.de/soap11/MailId", Order=0)]
        public EPiServer.Campaign.Extensions.MailId.getVersionResponseBody Body;
        
        public getVersionResponse() {
        }
        
        public getVersionResponse(EPiServer.Campaign.Extensions.MailId.getVersionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:api.broadmail.de/soap11/MailId")]
    public partial class getVersionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getVersionReturn;
        
        public getVersionResponseBody() {
        }
        
        public getVersionResponseBody(string getVersionReturn) {
            this.getVersionReturn = getVersionReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MailIdWebserviceChannel : EPiServer.Campaign.Extensions.MailId.MailIdWebservice, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MailIdWebserviceClient : System.ServiceModel.ClientBase<EPiServer.Campaign.Extensions.MailId.MailIdWebservice>, EPiServer.Campaign.Extensions.MailId.MailIdWebservice {
        
        public MailIdWebserviceClient() {
        }
        
        public MailIdWebserviceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MailIdWebserviceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailIdWebserviceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailIdWebserviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EPiServer.Campaign.Extensions.MailId.getMailingIdResponse EPiServer.Campaign.Extensions.MailId.MailIdWebservice.getMailingId(EPiServer.Campaign.Extensions.MailId.getMailingIdRequest request) {
            return base.Channel.getMailingId(request);
        }
        
        public long getMailingId(string in0, string in1) {
            EPiServer.Campaign.Extensions.MailId.getMailingIdRequest inValue = new EPiServer.Campaign.Extensions.MailId.getMailingIdRequest();
            inValue.Body = new EPiServer.Campaign.Extensions.MailId.getMailingIdRequestBody();
            inValue.Body.in0 = in0;
            inValue.Body.in1 = in1;
            EPiServer.Campaign.Extensions.MailId.getMailingIdResponse retVal = ((EPiServer.Campaign.Extensions.MailId.MailIdWebservice)(this)).getMailingId(inValue);
            return retVal.Body.getMailingIdReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.MailId.getMailingIdResponse> EPiServer.Campaign.Extensions.MailId.MailIdWebservice.getMailingIdAsync(EPiServer.Campaign.Extensions.MailId.getMailingIdRequest request) {
            return base.Channel.getMailingIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.MailId.getMailingIdResponse> getMailingIdAsync(string in0, string in1) {
            EPiServer.Campaign.Extensions.MailId.getMailingIdRequest inValue = new EPiServer.Campaign.Extensions.MailId.getMailingIdRequest();
            inValue.Body = new EPiServer.Campaign.Extensions.MailId.getMailingIdRequestBody();
            inValue.Body.in0 = in0;
            inValue.Body.in1 = in1;
            return ((EPiServer.Campaign.Extensions.MailId.MailIdWebservice)(this)).getMailingIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EPiServer.Campaign.Extensions.MailId.getRecipientListIdResponse EPiServer.Campaign.Extensions.MailId.MailIdWebservice.getRecipientListId(EPiServer.Campaign.Extensions.MailId.getRecipientListIdRequest request) {
            return base.Channel.getRecipientListId(request);
        }
        
        public long getRecipientListId(string in0, string in1) {
            EPiServer.Campaign.Extensions.MailId.getRecipientListIdRequest inValue = new EPiServer.Campaign.Extensions.MailId.getRecipientListIdRequest();
            inValue.Body = new EPiServer.Campaign.Extensions.MailId.getRecipientListIdRequestBody();
            inValue.Body.in0 = in0;
            inValue.Body.in1 = in1;
            EPiServer.Campaign.Extensions.MailId.getRecipientListIdResponse retVal = ((EPiServer.Campaign.Extensions.MailId.MailIdWebservice)(this)).getRecipientListId(inValue);
            return retVal.Body.getRecipientListIdReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.MailId.getRecipientListIdResponse> EPiServer.Campaign.Extensions.MailId.MailIdWebservice.getRecipientListIdAsync(EPiServer.Campaign.Extensions.MailId.getRecipientListIdRequest request) {
            return base.Channel.getRecipientListIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.MailId.getRecipientListIdResponse> getRecipientListIdAsync(string in0, string in1) {
            EPiServer.Campaign.Extensions.MailId.getRecipientListIdRequest inValue = new EPiServer.Campaign.Extensions.MailId.getRecipientListIdRequest();
            inValue.Body = new EPiServer.Campaign.Extensions.MailId.getRecipientListIdRequestBody();
            inValue.Body.in0 = in0;
            inValue.Body.in1 = in1;
            return ((EPiServer.Campaign.Extensions.MailId.MailIdWebservice)(this)).getRecipientListIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EPiServer.Campaign.Extensions.MailId.getRecipientIdResponse EPiServer.Campaign.Extensions.MailId.MailIdWebservice.getRecipientId(EPiServer.Campaign.Extensions.MailId.getRecipientIdRequest request) {
            return base.Channel.getRecipientId(request);
        }
        
        public string getRecipientId(string in0, string in1) {
            EPiServer.Campaign.Extensions.MailId.getRecipientIdRequest inValue = new EPiServer.Campaign.Extensions.MailId.getRecipientIdRequest();
            inValue.Body = new EPiServer.Campaign.Extensions.MailId.getRecipientIdRequestBody();
            inValue.Body.in0 = in0;
            inValue.Body.in1 = in1;
            EPiServer.Campaign.Extensions.MailId.getRecipientIdResponse retVal = ((EPiServer.Campaign.Extensions.MailId.MailIdWebservice)(this)).getRecipientId(inValue);
            return retVal.Body.getRecipientIdReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.MailId.getRecipientIdResponse> EPiServer.Campaign.Extensions.MailId.MailIdWebservice.getRecipientIdAsync(EPiServer.Campaign.Extensions.MailId.getRecipientIdRequest request) {
            return base.Channel.getRecipientIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.MailId.getRecipientIdResponse> getRecipientIdAsync(string in0, string in1) {
            EPiServer.Campaign.Extensions.MailId.getRecipientIdRequest inValue = new EPiServer.Campaign.Extensions.MailId.getRecipientIdRequest();
            inValue.Body = new EPiServer.Campaign.Extensions.MailId.getRecipientIdRequestBody();
            inValue.Body.in0 = in0;
            inValue.Body.in1 = in1;
            return ((EPiServer.Campaign.Extensions.MailId.MailIdWebservice)(this)).getRecipientIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EPiServer.Campaign.Extensions.MailId.getMandatorIdResponse EPiServer.Campaign.Extensions.MailId.MailIdWebservice.getMandatorId(EPiServer.Campaign.Extensions.MailId.getMandatorIdRequest request) {
            return base.Channel.getMandatorId(request);
        }
        
        public long getMandatorId(string in0, string in1) {
            EPiServer.Campaign.Extensions.MailId.getMandatorIdRequest inValue = new EPiServer.Campaign.Extensions.MailId.getMandatorIdRequest();
            inValue.Body = new EPiServer.Campaign.Extensions.MailId.getMandatorIdRequestBody();
            inValue.Body.in0 = in0;
            inValue.Body.in1 = in1;
            EPiServer.Campaign.Extensions.MailId.getMandatorIdResponse retVal = ((EPiServer.Campaign.Extensions.MailId.MailIdWebservice)(this)).getMandatorId(inValue);
            return retVal.Body.getMandatorIdReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.MailId.getMandatorIdResponse> EPiServer.Campaign.Extensions.MailId.MailIdWebservice.getMandatorIdAsync(EPiServer.Campaign.Extensions.MailId.getMandatorIdRequest request) {
            return base.Channel.getMandatorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.MailId.getMandatorIdResponse> getMandatorIdAsync(string in0, string in1) {
            EPiServer.Campaign.Extensions.MailId.getMandatorIdRequest inValue = new EPiServer.Campaign.Extensions.MailId.getMandatorIdRequest();
            inValue.Body = new EPiServer.Campaign.Extensions.MailId.getMandatorIdRequestBody();
            inValue.Body.in0 = in0;
            inValue.Body.in1 = in1;
            return ((EPiServer.Campaign.Extensions.MailId.MailIdWebservice)(this)).getMandatorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EPiServer.Campaign.Extensions.MailId.getVersionResponse EPiServer.Campaign.Extensions.MailId.MailIdWebservice.getVersion(EPiServer.Campaign.Extensions.MailId.getVersionRequest request) {
            return base.Channel.getVersion(request);
        }
        
        public string getVersion() {
            EPiServer.Campaign.Extensions.MailId.getVersionRequest inValue = new EPiServer.Campaign.Extensions.MailId.getVersionRequest();
            inValue.Body = new EPiServer.Campaign.Extensions.MailId.getVersionRequestBody();
            EPiServer.Campaign.Extensions.MailId.getVersionResponse retVal = ((EPiServer.Campaign.Extensions.MailId.MailIdWebservice)(this)).getVersion(inValue);
            return retVal.Body.getVersionReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.MailId.getVersionResponse> EPiServer.Campaign.Extensions.MailId.MailIdWebservice.getVersionAsync(EPiServer.Campaign.Extensions.MailId.getVersionRequest request) {
            return base.Channel.getVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.MailId.getVersionResponse> getVersionAsync() {
            EPiServer.Campaign.Extensions.MailId.getVersionRequest inValue = new EPiServer.Campaign.Extensions.MailId.getVersionRequest();
            inValue.Body = new EPiServer.Campaign.Extensions.MailId.getVersionRequestBody();
            return ((EPiServer.Campaign.Extensions.MailId.MailIdWebservice)(this)).getVersionAsync(inValue);
        }
    }
}
