//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPiServer.Campaign.Extensions.RecipientListService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:api.broadmail.de/soap11/RecipientList")]
    public partial class WebserviceException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object causeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public object cause {
            get {
                return this.causeField;
            }
            set {
                this.causeField = value;
                this.RaisePropertyChanged("cause");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:api.broadmail.de/soap11/RecipientList", ConfigurationName="RecipientListService.RecipientListWebservice")]
    public interface RecipientListWebservice {
        
        // CODEGEN: Parameter 'getAllIdsReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.RecipientListService.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getAllIdsReturn")]
        EPiServer.Campaign.Extensions.RecipientListService.getAllIdsResponse getAllIds(EPiServer.Campaign.Extensions.RecipientListService.getAllIdsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.RecipientListService.getAllIdsResponse> getAllIdsAsync(EPiServer.Campaign.Extensions.RecipientListService.getAllIdsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.RecipientListService.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void setTestRecipientList(string in0, long in1, bool in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task setTestRecipientListAsync(string in0, long in1, bool in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.RecipientListService.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="isTestRecipientListReturn")]
        bool isTestRecipientList(string in0, long in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="isTestRecipientListReturn")]
        System.Threading.Tasks.Task<bool> isTestRecipientListAsync(string in0, long in1);
        
        // CODEGEN: Parameter 'getDataSetReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.RecipientListService.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getDataSetReturn")]
        EPiServer.Campaign.Extensions.RecipientListService.getDataSetResponse getDataSet(EPiServer.Campaign.Extensions.RecipientListService.getDataSetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.RecipientListService.getDataSetResponse> getDataSetAsync(EPiServer.Campaign.Extensions.RecipientListService.getDataSetRequest request);
        
        // CODEGEN: Parameter 'getColumnNamesReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.RecipientListService.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getColumnNamesReturn")]
        EPiServer.Campaign.Extensions.RecipientListService.getColumnNamesResponse getColumnNames(EPiServer.Campaign.Extensions.RecipientListService.getColumnNamesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.RecipientListService.getColumnNamesResponse> getColumnNamesAsync(EPiServer.Campaign.Extensions.RecipientListService.getColumnNamesRequest request);
        
        // CODEGEN: Parameter 'getDataSetFlatReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.RecipientListService.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getDataSetFlatReturn")]
        EPiServer.Campaign.Extensions.RecipientListService.getDataSetFlatResponse getDataSetFlat(EPiServer.Campaign.Extensions.RecipientListService.getDataSetFlatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.RecipientListService.getDataSetFlatResponse> getDataSetFlatAsync(EPiServer.Campaign.Extensions.RecipientListService.getDataSetFlatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.RecipientListService.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getDescriptionReturn")]
        string getDescription(string in0, long in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getDescriptionReturn")]
        System.Threading.Tasks.Task<string> getDescriptionAsync(string in0, long in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.RecipientListService.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void setDescription(string in0, long in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task setDescriptionAsync(string in0, long in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.RecipientListService.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getCountReturn")]
        int getCount(string in0, bool in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getCountReturn")]
        System.Threading.Tasks.Task<int> getCountAsync(string in0, bool in1);
        
        // CODEGEN: Parameter 'getAttributeNamesReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.RecipientListService.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getAttributeNamesReturn")]
        EPiServer.Campaign.Extensions.RecipientListService.getAttributeNamesResponse getAttributeNames(EPiServer.Campaign.Extensions.RecipientListService.getAttributeNamesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.RecipientListService.getAttributeNamesResponse> getAttributeNamesAsync(EPiServer.Campaign.Extensions.RecipientListService.getAttributeNamesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.RecipientListService.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getNameReturn")]
        string getName(string in0, long in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getNameReturn")]
        System.Threading.Tasks.Task<string> getNameAsync(string in0, long in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.RecipientListService.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void setName(string in0, long in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task setNameAsync(string in0, long in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.RecipientListService.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="copyReturn")]
        long copy(string in0, long in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="copyReturn")]
        System.Threading.Tasks.Task<long> copyAsync(string in0, long in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPiServer.Campaign.Extensions.RecipientListService.WebserviceException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getVersionReturn")]
        string getVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getVersionReturn")]
        System.Threading.Tasks.Task<string> getVersionAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllIds", WrapperNamespace="urn:api.broadmail.de/soap11/RecipientList", IsWrapped=true)]
    public partial class getAllIdsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/RecipientList", Order=0)]
        public string in0;
        
        public getAllIdsRequest() {
        }
        
        public getAllIdsRequest(string in0) {
            this.in0 = in0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllIdsResponse", WrapperNamespace="urn:api.broadmail.de/soap11/RecipientList", IsWrapped=true)]
    public partial class getAllIdsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/RecipientList", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getAllIdsReturn")]
        public long[] getAllIdsReturn;
        
        public getAllIdsResponse() {
        }
        
        public getAllIdsResponse(long[] getAllIdsReturn) {
            this.getAllIdsReturn = getAllIdsReturn;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:api.broadmail.de/soap11/RecipientList")]
    public partial class ArrayOf_xsd_string : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("item", Order=0)]
        public string[] item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDataSet", WrapperNamespace="urn:api.broadmail.de/soap11/RecipientList", IsWrapped=true)]
    public partial class getDataSetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/RecipientList", Order=0)]
        public string in0;
        
        public getDataSetRequest() {
        }
        
        public getDataSetRequest(string in0) {
            this.in0 = in0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDataSetResponse", WrapperNamespace="urn:api.broadmail.de/soap11/RecipientList", IsWrapped=true)]
    public partial class getDataSetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/RecipientList", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getDataSetReturn")]
        public EPiServer.Campaign.Extensions.RecipientListService.ArrayOf_xsd_string[] getDataSetReturn;
        
        public getDataSetResponse() {
        }
        
        public getDataSetResponse(EPiServer.Campaign.Extensions.RecipientListService.ArrayOf_xsd_string[] getDataSetReturn) {
            this.getDataSetReturn = getDataSetReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getColumnNames", WrapperNamespace="urn:api.broadmail.de/soap11/RecipientList", IsWrapped=true)]
    public partial class getColumnNamesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/RecipientList", Order=0)]
        public string in0;
        
        public getColumnNamesRequest() {
        }
        
        public getColumnNamesRequest(string in0) {
            this.in0 = in0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getColumnNamesResponse", WrapperNamespace="urn:api.broadmail.de/soap11/RecipientList", IsWrapped=true)]
    public partial class getColumnNamesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/RecipientList", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getColumnNamesReturn")]
        public string[] getColumnNamesReturn;
        
        public getColumnNamesResponse() {
        }
        
        public getColumnNamesResponse(string[] getColumnNamesReturn) {
            this.getColumnNamesReturn = getColumnNamesReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDataSetFlat", WrapperNamespace="urn:api.broadmail.de/soap11/RecipientList", IsWrapped=true)]
    public partial class getDataSetFlatRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/RecipientList", Order=0)]
        public string in0;
        
        public getDataSetFlatRequest() {
        }
        
        public getDataSetFlatRequest(string in0) {
            this.in0 = in0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDataSetFlatResponse", WrapperNamespace="urn:api.broadmail.de/soap11/RecipientList", IsWrapped=true)]
    public partial class getDataSetFlatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/RecipientList", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getDataSetFlatReturn")]
        public string[] getDataSetFlatReturn;
        
        public getDataSetFlatResponse() {
        }
        
        public getDataSetFlatResponse(string[] getDataSetFlatReturn) {
            this.getDataSetFlatReturn = getDataSetFlatReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAttributeNames", WrapperNamespace="urn:api.broadmail.de/soap11/RecipientList", IsWrapped=true)]
    public partial class getAttributeNamesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/RecipientList", Order=0)]
        public string in0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/RecipientList", Order=1)]
        public long in1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/RecipientList", Order=2)]
        public string in2;
        
        public getAttributeNamesRequest() {
        }
        
        public getAttributeNamesRequest(string in0, long in1, string in2) {
            this.in0 = in0;
            this.in1 = in1;
            this.in2 = in2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAttributeNamesResponse", WrapperNamespace="urn:api.broadmail.de/soap11/RecipientList", IsWrapped=true)]
    public partial class getAttributeNamesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:api.broadmail.de/soap11/RecipientList", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getAttributeNamesReturn")]
        public string[] getAttributeNamesReturn;
        
        public getAttributeNamesResponse() {
        }
        
        public getAttributeNamesResponse(string[] getAttributeNamesReturn) {
            this.getAttributeNamesReturn = getAttributeNamesReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RecipientListWebserviceChannel : EPiServer.Campaign.Extensions.RecipientListService.RecipientListWebservice, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecipientListWebserviceClient : System.ServiceModel.ClientBase<EPiServer.Campaign.Extensions.RecipientListService.RecipientListWebservice>, EPiServer.Campaign.Extensions.RecipientListService.RecipientListWebservice {
        
        public RecipientListWebserviceClient() {
        }
        
        public RecipientListWebserviceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RecipientListWebserviceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecipientListWebserviceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecipientListWebserviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EPiServer.Campaign.Extensions.RecipientListService.getAllIdsResponse EPiServer.Campaign.Extensions.RecipientListService.RecipientListWebservice.getAllIds(EPiServer.Campaign.Extensions.RecipientListService.getAllIdsRequest request) {
            return base.Channel.getAllIds(request);
        }
        
        public long[] getAllIds(string in0) {
            EPiServer.Campaign.Extensions.RecipientListService.getAllIdsRequest inValue = new EPiServer.Campaign.Extensions.RecipientListService.getAllIdsRequest();
            inValue.in0 = in0;
            EPiServer.Campaign.Extensions.RecipientListService.getAllIdsResponse retVal = ((EPiServer.Campaign.Extensions.RecipientListService.RecipientListWebservice)(this)).getAllIds(inValue);
            return retVal.getAllIdsReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.RecipientListService.getAllIdsResponse> EPiServer.Campaign.Extensions.RecipientListService.RecipientListWebservice.getAllIdsAsync(EPiServer.Campaign.Extensions.RecipientListService.getAllIdsRequest request) {
            return base.Channel.getAllIdsAsync(request);
        }
        
        public System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.RecipientListService.getAllIdsResponse> getAllIdsAsync(string in0) {
            EPiServer.Campaign.Extensions.RecipientListService.getAllIdsRequest inValue = new EPiServer.Campaign.Extensions.RecipientListService.getAllIdsRequest();
            inValue.in0 = in0;
            return ((EPiServer.Campaign.Extensions.RecipientListService.RecipientListWebservice)(this)).getAllIdsAsync(inValue);
        }
        
        public void setTestRecipientList(string in0, long in1, bool in2) {
            base.Channel.setTestRecipientList(in0, in1, in2);
        }
        
        public System.Threading.Tasks.Task setTestRecipientListAsync(string in0, long in1, bool in2) {
            return base.Channel.setTestRecipientListAsync(in0, in1, in2);
        }
        
        public bool isTestRecipientList(string in0, long in1) {
            return base.Channel.isTestRecipientList(in0, in1);
        }
        
        public System.Threading.Tasks.Task<bool> isTestRecipientListAsync(string in0, long in1) {
            return base.Channel.isTestRecipientListAsync(in0, in1);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EPiServer.Campaign.Extensions.RecipientListService.getDataSetResponse EPiServer.Campaign.Extensions.RecipientListService.RecipientListWebservice.getDataSet(EPiServer.Campaign.Extensions.RecipientListService.getDataSetRequest request) {
            return base.Channel.getDataSet(request);
        }
        
        public EPiServer.Campaign.Extensions.RecipientListService.ArrayOf_xsd_string[] getDataSet(string in0) {
            EPiServer.Campaign.Extensions.RecipientListService.getDataSetRequest inValue = new EPiServer.Campaign.Extensions.RecipientListService.getDataSetRequest();
            inValue.in0 = in0;
            EPiServer.Campaign.Extensions.RecipientListService.getDataSetResponse retVal = ((EPiServer.Campaign.Extensions.RecipientListService.RecipientListWebservice)(this)).getDataSet(inValue);
            return retVal.getDataSetReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.RecipientListService.getDataSetResponse> EPiServer.Campaign.Extensions.RecipientListService.RecipientListWebservice.getDataSetAsync(EPiServer.Campaign.Extensions.RecipientListService.getDataSetRequest request) {
            return base.Channel.getDataSetAsync(request);
        }
        
        public System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.RecipientListService.getDataSetResponse> getDataSetAsync(string in0) {
            EPiServer.Campaign.Extensions.RecipientListService.getDataSetRequest inValue = new EPiServer.Campaign.Extensions.RecipientListService.getDataSetRequest();
            inValue.in0 = in0;
            return ((EPiServer.Campaign.Extensions.RecipientListService.RecipientListWebservice)(this)).getDataSetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EPiServer.Campaign.Extensions.RecipientListService.getColumnNamesResponse EPiServer.Campaign.Extensions.RecipientListService.RecipientListWebservice.getColumnNames(EPiServer.Campaign.Extensions.RecipientListService.getColumnNamesRequest request) {
            return base.Channel.getColumnNames(request);
        }
        
        public string[] getColumnNames(string in0) {
            EPiServer.Campaign.Extensions.RecipientListService.getColumnNamesRequest inValue = new EPiServer.Campaign.Extensions.RecipientListService.getColumnNamesRequest();
            inValue.in0 = in0;
            EPiServer.Campaign.Extensions.RecipientListService.getColumnNamesResponse retVal = ((EPiServer.Campaign.Extensions.RecipientListService.RecipientListWebservice)(this)).getColumnNames(inValue);
            return retVal.getColumnNamesReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.RecipientListService.getColumnNamesResponse> EPiServer.Campaign.Extensions.RecipientListService.RecipientListWebservice.getColumnNamesAsync(EPiServer.Campaign.Extensions.RecipientListService.getColumnNamesRequest request) {
            return base.Channel.getColumnNamesAsync(request);
        }
        
        public System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.RecipientListService.getColumnNamesResponse> getColumnNamesAsync(string in0) {
            EPiServer.Campaign.Extensions.RecipientListService.getColumnNamesRequest inValue = new EPiServer.Campaign.Extensions.RecipientListService.getColumnNamesRequest();
            inValue.in0 = in0;
            return ((EPiServer.Campaign.Extensions.RecipientListService.RecipientListWebservice)(this)).getColumnNamesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EPiServer.Campaign.Extensions.RecipientListService.getDataSetFlatResponse EPiServer.Campaign.Extensions.RecipientListService.RecipientListWebservice.getDataSetFlat(EPiServer.Campaign.Extensions.RecipientListService.getDataSetFlatRequest request) {
            return base.Channel.getDataSetFlat(request);
        }
        
        public string[] getDataSetFlat(string in0) {
            EPiServer.Campaign.Extensions.RecipientListService.getDataSetFlatRequest inValue = new EPiServer.Campaign.Extensions.RecipientListService.getDataSetFlatRequest();
            inValue.in0 = in0;
            EPiServer.Campaign.Extensions.RecipientListService.getDataSetFlatResponse retVal = ((EPiServer.Campaign.Extensions.RecipientListService.RecipientListWebservice)(this)).getDataSetFlat(inValue);
            return retVal.getDataSetFlatReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.RecipientListService.getDataSetFlatResponse> EPiServer.Campaign.Extensions.RecipientListService.RecipientListWebservice.getDataSetFlatAsync(EPiServer.Campaign.Extensions.RecipientListService.getDataSetFlatRequest request) {
            return base.Channel.getDataSetFlatAsync(request);
        }
        
        public System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.RecipientListService.getDataSetFlatResponse> getDataSetFlatAsync(string in0) {
            EPiServer.Campaign.Extensions.RecipientListService.getDataSetFlatRequest inValue = new EPiServer.Campaign.Extensions.RecipientListService.getDataSetFlatRequest();
            inValue.in0 = in0;
            return ((EPiServer.Campaign.Extensions.RecipientListService.RecipientListWebservice)(this)).getDataSetFlatAsync(inValue);
        }
        
        public string getDescription(string in0, long in1) {
            return base.Channel.getDescription(in0, in1);
        }
        
        public System.Threading.Tasks.Task<string> getDescriptionAsync(string in0, long in1) {
            return base.Channel.getDescriptionAsync(in0, in1);
        }
        
        public void setDescription(string in0, long in1, string in2) {
            base.Channel.setDescription(in0, in1, in2);
        }
        
        public System.Threading.Tasks.Task setDescriptionAsync(string in0, long in1, string in2) {
            return base.Channel.setDescriptionAsync(in0, in1, in2);
        }
        
        public int getCount(string in0, bool in1) {
            return base.Channel.getCount(in0, in1);
        }
        
        public System.Threading.Tasks.Task<int> getCountAsync(string in0, bool in1) {
            return base.Channel.getCountAsync(in0, in1);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EPiServer.Campaign.Extensions.RecipientListService.getAttributeNamesResponse EPiServer.Campaign.Extensions.RecipientListService.RecipientListWebservice.getAttributeNames(EPiServer.Campaign.Extensions.RecipientListService.getAttributeNamesRequest request) {
            return base.Channel.getAttributeNames(request);
        }
        
        public string[] getAttributeNames(string in0, long in1, string in2) {
            EPiServer.Campaign.Extensions.RecipientListService.getAttributeNamesRequest inValue = new EPiServer.Campaign.Extensions.RecipientListService.getAttributeNamesRequest();
            inValue.in0 = in0;
            inValue.in1 = in1;
            inValue.in2 = in2;
            EPiServer.Campaign.Extensions.RecipientListService.getAttributeNamesResponse retVal = ((EPiServer.Campaign.Extensions.RecipientListService.RecipientListWebservice)(this)).getAttributeNames(inValue);
            return retVal.getAttributeNamesReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.RecipientListService.getAttributeNamesResponse> EPiServer.Campaign.Extensions.RecipientListService.RecipientListWebservice.getAttributeNamesAsync(EPiServer.Campaign.Extensions.RecipientListService.getAttributeNamesRequest request) {
            return base.Channel.getAttributeNamesAsync(request);
        }
        
        public System.Threading.Tasks.Task<EPiServer.Campaign.Extensions.RecipientListService.getAttributeNamesResponse> getAttributeNamesAsync(string in0, long in1, string in2) {
            EPiServer.Campaign.Extensions.RecipientListService.getAttributeNamesRequest inValue = new EPiServer.Campaign.Extensions.RecipientListService.getAttributeNamesRequest();
            inValue.in0 = in0;
            inValue.in1 = in1;
            inValue.in2 = in2;
            return ((EPiServer.Campaign.Extensions.RecipientListService.RecipientListWebservice)(this)).getAttributeNamesAsync(inValue);
        }
        
        public string getName(string in0, long in1) {
            return base.Channel.getName(in0, in1);
        }
        
        public System.Threading.Tasks.Task<string> getNameAsync(string in0, long in1) {
            return base.Channel.getNameAsync(in0, in1);
        }
        
        public void setName(string in0, long in1, string in2) {
            base.Channel.setName(in0, in1, in2);
        }
        
        public System.Threading.Tasks.Task setNameAsync(string in0, long in1, string in2) {
            return base.Channel.setNameAsync(in0, in1, in2);
        }
        
        public long copy(string in0, long in1) {
            return base.Channel.copy(in0, in1);
        }
        
        public System.Threading.Tasks.Task<long> copyAsync(string in0, long in1) {
            return base.Channel.copyAsync(in0, in1);
        }
        
        public string getVersion() {
            return base.Channel.getVersion();
        }
        
        public System.Threading.Tasks.Task<string> getVersionAsync() {
            return base.Channel.getVersionAsync();
        }
    }
}
